// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: v1/event/seating.proto

package event

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SeatingPlan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizerId   int64                  `protobuf:"varint,2,opt,name=organizer_id,json=organizerId,proto3" json:"organizer_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Layout        string                 `protobuf:"bytes,4,opt,name=layout,proto3" json:"layout,omitempty"` // JSON string (empty {} in Phase 1; render coords in Phase 2)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeatingPlan) Reset() {
	*x = SeatingPlan{}
	mi := &file_v1_event_seating_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeatingPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatingPlan) ProtoMessage() {}

func (x *SeatingPlan) ProtoReflect() protoreflect.Message {
	mi := &file_v1_event_seating_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatingPlan.ProtoReflect.Descriptor instead.
func (*SeatingPlan) Descriptor() ([]byte, []int) {
	return file_v1_event_seating_proto_rawDescGZIP(), []int{0}
}

func (x *SeatingPlan) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SeatingPlan) GetOrganizerId() int64 {
	if x != nil {
		return x.OrganizerId
	}
	return 0
}

func (x *SeatingPlan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SeatingPlan) GetLayout() string {
	if x != nil {
		return x.Layout
	}
	return ""
}

type CreateSeatingPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organizer     string                 `protobuf:"bytes,1,opt,name=organizer,proto3" json:"organizer,omitempty"` // organizer slug
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Layout        string                 `protobuf:"bytes,3,opt,name=layout,proto3" json:"layout,omitempty"` // JSON string (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSeatingPlanRequest) Reset() {
	*x = CreateSeatingPlanRequest{}
	mi := &file_v1_event_seating_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSeatingPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSeatingPlanRequest) ProtoMessage() {}

func (x *CreateSeatingPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_event_seating_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSeatingPlanRequest.ProtoReflect.Descriptor instead.
func (*CreateSeatingPlanRequest) Descriptor() ([]byte, []int) {
	return file_v1_event_seating_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSeatingPlanRequest) GetOrganizer() string {
	if x != nil {
		return x.Organizer
	}
	return ""
}

func (x *CreateSeatingPlanRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSeatingPlanRequest) GetLayout() string {
	if x != nil {
		return x.Layout
	}
	return ""
}

type SeatingPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Plan          *SeatingPlan           `protobuf:"bytes,2,opt,name=plan,proto3" json:"plan,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeatingPlanResponse) Reset() {
	*x = SeatingPlanResponse{}
	mi := &file_v1_event_seating_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeatingPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatingPlanResponse) ProtoMessage() {}

func (x *SeatingPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_event_seating_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatingPlanResponse.ProtoReflect.Descriptor instead.
func (*SeatingPlanResponse) Descriptor() ([]byte, []int) {
	return file_v1_event_seating_proto_rawDescGZIP(), []int{2}
}

func (x *SeatingPlanResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SeatingPlanResponse) GetPlan() *SeatingPlan {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *SeatingPlanResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *SeatingPlanResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ListSeatingPlansRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organizer     string                 `protobuf:"bytes,1,opt,name=organizer,proto3" json:"organizer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSeatingPlansRequest) Reset() {
	*x = ListSeatingPlansRequest{}
	mi := &file_v1_event_seating_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSeatingPlansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSeatingPlansRequest) ProtoMessage() {}

func (x *ListSeatingPlansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_event_seating_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSeatingPlansRequest.ProtoReflect.Descriptor instead.
func (*ListSeatingPlansRequest) Descriptor() ([]byte, []int) {
	return file_v1_event_seating_proto_rawDescGZIP(), []int{3}
}

func (x *ListSeatingPlansRequest) GetOrganizer() string {
	if x != nil {
		return x.Organizer
	}
	return ""
}

type ListSeatingPlansResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Plans         []*SeatingPlan         `protobuf:"bytes,2,rep,name=plans,proto3" json:"plans,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSeatingPlansResponse) Reset() {
	*x = ListSeatingPlansResponse{}
	mi := &file_v1_event_seating_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSeatingPlansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSeatingPlansResponse) ProtoMessage() {}

func (x *ListSeatingPlansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_event_seating_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSeatingPlansResponse.ProtoReflect.Descriptor instead.
func (*ListSeatingPlansResponse) Descriptor() ([]byte, []int) {
	return file_v1_event_seating_proto_rawDescGZIP(), []int{4}
}

func (x *ListSeatingPlansResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListSeatingPlansResponse) GetPlans() []*SeatingPlan {
	if x != nil {
		return x.Plans
	}
	return nil
}

func (x *ListSeatingPlansResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type SeatImport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatGuid      string                 `protobuf:"bytes,1,opt,name=seat_guid,json=seatGuid,proto3" json:"seat_guid,omitempty"`
	ZoneName      string                 `protobuf:"bytes,2,opt,name=zone_name,json=zoneName,proto3" json:"zone_name,omitempty"`
	RowName       string                 `protobuf:"bytes,3,opt,name=row_name,json=rowName,proto3" json:"row_name,omitempty"`
	RowLabel      string                 `protobuf:"bytes,4,opt,name=row_label,json=rowLabel,proto3" json:"row_label,omitempty"`
	SeatNumber    string                 `protobuf:"bytes,5,opt,name=seat_number,json=seatNumber,proto3" json:"seat_number,omitempty"`
	SeatLabel     string                 `protobuf:"bytes,6,opt,name=seat_label,json=seatLabel,proto3" json:"seat_label,omitempty"`
	SortingRank   int64                  `protobuf:"varint,7,opt,name=sorting_rank,json=sortingRank,proto3" json:"sorting_rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeatImport) Reset() {
	*x = SeatImport{}
	mi := &file_v1_event_seating_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeatImport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatImport) ProtoMessage() {}

func (x *SeatImport) ProtoReflect() protoreflect.Message {
	mi := &file_v1_event_seating_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatImport.ProtoReflect.Descriptor instead.
func (*SeatImport) Descriptor() ([]byte, []int) {
	return file_v1_event_seating_proto_rawDescGZIP(), []int{5}
}

func (x *SeatImport) GetSeatGuid() string {
	if x != nil {
		return x.SeatGuid
	}
	return ""
}

func (x *SeatImport) GetZoneName() string {
	if x != nil {
		return x.ZoneName
	}
	return ""
}

func (x *SeatImport) GetRowName() string {
	if x != nil {
		return x.RowName
	}
	return ""
}

func (x *SeatImport) GetRowLabel() string {
	if x != nil {
		return x.RowLabel
	}
	return ""
}

func (x *SeatImport) GetSeatNumber() string {
	if x != nil {
		return x.SeatNumber
	}
	return ""
}

func (x *SeatImport) GetSeatLabel() string {
	if x != nil {
		return x.SeatLabel
	}
	return ""
}

func (x *SeatImport) GetSortingRank() int64 {
	if x != nil {
		return x.SortingRank
	}
	return 0
}

type ImportSeatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organizer     string                 `protobuf:"bytes,1,opt,name=organizer,proto3" json:"organizer,omitempty"`                                 // organizer slug
	Event         string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`                                         // event slug
	SubeventId    int64                  `protobuf:"varint,3,opt,name=subevent_id,json=subeventId,proto3" json:"subevent_id,omitempty"`            // 0 = event-wide (no subevent)
	SeatingPlanId int64                  `protobuf:"varint,4,opt,name=seating_plan_id,json=seatingPlanId,proto3" json:"seating_plan_id,omitempty"` // plan to attach to the event (marks it seated)
	Seats         []*SeatImport          `protobuf:"bytes,5,rep,name=seats,proto3" json:"seats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportSeatsRequest) Reset() {
	*x = ImportSeatsRequest{}
	mi := &file_v1_event_seating_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportSeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportSeatsRequest) ProtoMessage() {}

func (x *ImportSeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_event_seating_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportSeatsRequest.ProtoReflect.Descriptor instead.
func (*ImportSeatsRequest) Descriptor() ([]byte, []int) {
	return file_v1_event_seating_proto_rawDescGZIP(), []int{6}
}

func (x *ImportSeatsRequest) GetOrganizer() string {
	if x != nil {
		return x.Organizer
	}
	return ""
}

func (x *ImportSeatsRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *ImportSeatsRequest) GetSubeventId() int64 {
	if x != nil {
		return x.SubeventId
	}
	return 0
}

func (x *ImportSeatsRequest) GetSeatingPlanId() int64 {
	if x != nil {
		return x.SeatingPlanId
	}
	return 0
}

func (x *ImportSeatsRequest) GetSeats() []*SeatImport {
	if x != nil {
		return x.Seats
	}
	return nil
}

type ImportSeatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Imported      int32                  `protobuf:"varint,2,opt,name=imported,proto3" json:"imported,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportSeatsResponse) Reset() {
	*x = ImportSeatsResponse{}
	mi := &file_v1_event_seating_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportSeatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportSeatsResponse) ProtoMessage() {}

func (x *ImportSeatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_event_seating_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportSeatsResponse.ProtoReflect.Descriptor instead.
func (*ImportSeatsResponse) Descriptor() ([]byte, []int) {
	return file_v1_event_seating_proto_rawDescGZIP(), []int{7}
}

func (x *ImportSeatsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ImportSeatsResponse) GetImported() int32 {
	if x != nil {
		return x.Imported
	}
	return 0
}

func (x *ImportSeatsResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ImportSeatsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type SeatCategoryMappingInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LayoutCategory string                 `protobuf:"bytes,1,opt,name=layout_category,json=layoutCategory,proto3" json:"layout_category,omitempty"` // zone name
	ProductId      int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`               // item id this zone sells
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SeatCategoryMappingInput) Reset() {
	*x = SeatCategoryMappingInput{}
	mi := &file_v1_event_seating_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeatCategoryMappingInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatCategoryMappingInput) ProtoMessage() {}

func (x *SeatCategoryMappingInput) ProtoReflect() protoreflect.Message {
	mi := &file_v1_event_seating_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatCategoryMappingInput.ProtoReflect.Descriptor instead.
func (*SeatCategoryMappingInput) Descriptor() ([]byte, []int) {
	return file_v1_event_seating_proto_rawDescGZIP(), []int{8}
}

func (x *SeatCategoryMappingInput) GetLayoutCategory() string {
	if x != nil {
		return x.LayoutCategory
	}
	return ""
}

func (x *SeatCategoryMappingInput) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type SetSeatCategoryMappingsRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Organizer     string                      `protobuf:"bytes,1,opt,name=organizer,proto3" json:"organizer,omitempty"`
	Event         string                      `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	SubeventId    int64                       `protobuf:"varint,3,opt,name=subevent_id,json=subeventId,proto3" json:"subevent_id,omitempty"`
	Mappings      []*SeatCategoryMappingInput `protobuf:"bytes,4,rep,name=mappings,proto3" json:"mappings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSeatCategoryMappingsRequest) Reset() {
	*x = SetSeatCategoryMappingsRequest{}
	mi := &file_v1_event_seating_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSeatCategoryMappingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSeatCategoryMappingsRequest) ProtoMessage() {}

func (x *SetSeatCategoryMappingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_event_seating_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSeatCategoryMappingsRequest.ProtoReflect.Descriptor instead.
func (*SetSeatCategoryMappingsRequest) Descriptor() ([]byte, []int) {
	return file_v1_event_seating_proto_rawDescGZIP(), []int{9}
}

func (x *SetSeatCategoryMappingsRequest) GetOrganizer() string {
	if x != nil {
		return x.Organizer
	}
	return ""
}

func (x *SetSeatCategoryMappingsRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *SetSeatCategoryMappingsRequest) GetSubeventId() int64 {
	if x != nil {
		return x.SubeventId
	}
	return 0
}

func (x *SetSeatCategoryMappingsRequest) GetMappings() []*SeatCategoryMappingInput {
	if x != nil {
		return x.Mappings
	}
	return nil
}

type SetSeatCategoryMappingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSeatCategoryMappingsResponse) Reset() {
	*x = SetSeatCategoryMappingsResponse{}
	mi := &file_v1_event_seating_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSeatCategoryMappingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSeatCategoryMappingsResponse) ProtoMessage() {}

func (x *SetSeatCategoryMappingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_event_seating_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSeatCategoryMappingsResponse.ProtoReflect.Descriptor instead.
func (*SetSeatCategoryMappingsResponse) Descriptor() ([]byte, []int) {
	return file_v1_event_seating_proto_rawDescGZIP(), []int{10}
}

func (x *SetSeatCategoryMappingsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetSeatCategoryMappingsResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *SetSeatCategoryMappingsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type AssignSeatingPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organizer     string                 `protobuf:"bytes,1,opt,name=organizer,proto3" json:"organizer,omitempty"`
	Event         string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	SeatingPlanId int64                  `protobuf:"varint,3,opt,name=seating_plan_id,json=seatingPlanId,proto3" json:"seating_plan_id,omitempty"` // 0 = unassign (general admission)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignSeatingPlanRequest) Reset() {
	*x = AssignSeatingPlanRequest{}
	mi := &file_v1_event_seating_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignSeatingPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignSeatingPlanRequest) ProtoMessage() {}

func (x *AssignSeatingPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_event_seating_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignSeatingPlanRequest.ProtoReflect.Descriptor instead.
func (*AssignSeatingPlanRequest) Descriptor() ([]byte, []int) {
	return file_v1_event_seating_proto_rawDescGZIP(), []int{11}
}

func (x *AssignSeatingPlanRequest) GetOrganizer() string {
	if x != nil {
		return x.Organizer
	}
	return ""
}

func (x *AssignSeatingPlanRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *AssignSeatingPlanRequest) GetSeatingPlanId() int64 {
	if x != nil {
		return x.SeatingPlanId
	}
	return 0
}

type AssignSeatingPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignSeatingPlanResponse) Reset() {
	*x = AssignSeatingPlanResponse{}
	mi := &file_v1_event_seating_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignSeatingPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignSeatingPlanResponse) ProtoMessage() {}

func (x *AssignSeatingPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_event_seating_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignSeatingPlanResponse.ProtoReflect.Descriptor instead.
func (*AssignSeatingPlanResponse) Descriptor() ([]byte, []int) {
	return file_v1_event_seating_proto_rawDescGZIP(), []int{12}
}

func (x *AssignSeatingPlanResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AssignSeatingPlanResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_v1_event_seating_proto protoreflect.FileDescriptor

const file_v1_event_seating_proto_rawDesc = "" +
	"\n" +
	"\x16v1/event/seating.proto\x12\x0friptik.event.v1\"l\n" +
	"\vSeatingPlan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\forganizer_id\x18\x02 \x01(\x03R\vorganizerId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06layout\x18\x04 \x01(\tR\x06layout\"d\n" +
	"\x18CreateSeatingPlanRequest\x12\x1c\n" +
	"\torganizer\x18\x01 \x01(\tR\torganizer\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06layout\x18\x03 \x01(\tR\x06layout\"\xa5\x01\n" +
	"\x13SeatingPlanResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x120\n" +
	"\x04plan\x18\x02 \x01(\v2\x1c.riptik.event.v1.SeatingPlanR\x04plan\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"7\n" +
	"\x17ListSeatingPlansRequest\x12\x1c\n" +
	"\torganizer\x18\x01 \x01(\tR\torganizer\"\x8d\x01\n" +
	"\x18ListSeatingPlansResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x122\n" +
	"\x05plans\x18\x02 \x03(\v2\x1c.riptik.event.v1.SeatingPlanR\x05plans\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xe1\x01\n" +
	"\n" +
	"SeatImport\x12\x1b\n" +
	"\tseat_guid\x18\x01 \x01(\tR\bseatGuid\x12\x1b\n" +
	"\tzone_name\x18\x02 \x01(\tR\bzoneName\x12\x19\n" +
	"\brow_name\x18\x03 \x01(\tR\arowName\x12\x1b\n" +
	"\trow_label\x18\x04 \x01(\tR\browLabel\x12\x1f\n" +
	"\vseat_number\x18\x05 \x01(\tR\n" +
	"seatNumber\x12\x1d\n" +
	"\n" +
	"seat_label\x18\x06 \x01(\tR\tseatLabel\x12!\n" +
	"\fsorting_rank\x18\a \x01(\x03R\vsortingRank\"\xc4\x01\n" +
	"\x12ImportSeatsRequest\x12\x1c\n" +
	"\torganizer\x18\x01 \x01(\tR\torganizer\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12\x1f\n" +
	"\vsubevent_id\x18\x03 \x01(\x03R\n" +
	"subeventId\x12&\n" +
	"\x0fseating_plan_id\x18\x04 \x01(\x03R\rseatingPlanId\x121\n" +
	"\x05seats\x18\x05 \x03(\v2\x1b.riptik.event.v1.SeatImportR\x05seats\"\x8f\x01\n" +
	"\x13ImportSeatsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1a\n" +
	"\bimported\x18\x02 \x01(\x05R\bimported\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"b\n" +
	"\x18SeatCategoryMappingInput\x12'\n" +
	"\x0flayout_category\x18\x01 \x01(\tR\x0elayoutCategory\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\"\xbc\x01\n" +
	"\x1eSetSeatCategoryMappingsRequest\x12\x1c\n" +
	"\torganizer\x18\x01 \x01(\tR\torganizer\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12\x1f\n" +
	"\vsubevent_id\x18\x03 \x01(\x03R\n" +
	"subeventId\x12E\n" +
	"\bmappings\x18\x04 \x03(\v2).riptik.event.v1.SeatCategoryMappingInputR\bmappings\"\x7f\n" +
	"\x1fSetSeatCategoryMappingsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"v\n" +
	"\x18AssignSeatingPlanRequest\x12\x1c\n" +
	"\torganizer\x18\x01 \x01(\tR\torganizer\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12&\n" +
	"\x0fseating_plan_id\x18\x03 \x01(\x03R\rseatingPlanId\"Z\n" +
	"\x19AssignSeatingPlanResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessageB(Z&github.com/riptik/services/pb/v1/eventb\x06proto3"

var (
	file_v1_event_seating_proto_rawDescOnce sync.Once
	file_v1_event_seating_proto_rawDescData []byte
)

func file_v1_event_seating_proto_rawDescGZIP() []byte {
	file_v1_event_seating_proto_rawDescOnce.Do(func() {
		file_v1_event_seating_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_event_seating_proto_rawDesc), len(file_v1_event_seating_proto_rawDesc)))
	})
	return file_v1_event_seating_proto_rawDescData
}

var file_v1_event_seating_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_v1_event_seating_proto_goTypes = []any{
	(*SeatingPlan)(nil),                     // 0: riptik.event.v1.SeatingPlan
	(*CreateSeatingPlanRequest)(nil),        // 1: riptik.event.v1.CreateSeatingPlanRequest
	(*SeatingPlanResponse)(nil),             // 2: riptik.event.v1.SeatingPlanResponse
	(*ListSeatingPlansRequest)(nil),         // 3: riptik.event.v1.ListSeatingPlansRequest
	(*ListSeatingPlansResponse)(nil),        // 4: riptik.event.v1.ListSeatingPlansResponse
	(*SeatImport)(nil),                      // 5: riptik.event.v1.SeatImport
	(*ImportSeatsRequest)(nil),              // 6: riptik.event.v1.ImportSeatsRequest
	(*ImportSeatsResponse)(nil),             // 7: riptik.event.v1.ImportSeatsResponse
	(*SeatCategoryMappingInput)(nil),        // 8: riptik.event.v1.SeatCategoryMappingInput
	(*SetSeatCategoryMappingsRequest)(nil),  // 9: riptik.event.v1.SetSeatCategoryMappingsRequest
	(*SetSeatCategoryMappingsResponse)(nil), // 10: riptik.event.v1.SetSeatCategoryMappingsResponse
	(*AssignSeatingPlanRequest)(nil),        // 11: riptik.event.v1.AssignSeatingPlanRequest
	(*AssignSeatingPlanResponse)(nil),       // 12: riptik.event.v1.AssignSeatingPlanResponse
}
var file_v1_event_seating_proto_depIdxs = []int32{
	0, // 0: riptik.event.v1.SeatingPlanResponse.plan:type_name -> riptik.event.v1.SeatingPlan
	0, // 1: riptik.event.v1.ListSeatingPlansResponse.plans:type_name -> riptik.event.v1.SeatingPlan
	5, // 2: riptik.event.v1.ImportSeatsRequest.seats:type_name -> riptik.event.v1.SeatImport
	8, // 3: riptik.event.v1.SetSeatCategoryMappingsRequest.mappings:type_name -> riptik.event.v1.SeatCategoryMappingInput
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_v1_event_seating_proto_init() }
func file_v1_event_seating_proto_init() {
	if File_v1_event_seating_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_event_seating_proto_rawDesc), len(file_v1_event_seating_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_event_seating_proto_goTypes,
		DependencyIndexes: file_v1_event_seating_proto_depIdxs,
		MessageInfos:      file_v1_event_seating_proto_msgTypes,
	}.Build()
	File_v1_event_seating_proto = out.File
	file_v1_event_seating_proto_goTypes = nil
	file_v1_event_seating_proto_depIdxs = nil
}
