// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: v1/booking/order.proto

package booking

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request: List orders (Pretix API format)
type ListOrdersRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Organizer       string                 `protobuf:"bytes,1,opt,name=organizer,proto3" json:"organizer,omitempty"`                                      // Organizer slug (required)
	Event           string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`                                              // Event slug (required)
	Page            int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                                               // Page number (default: 1)
	Ordering        string                 `protobuf:"bytes,4,opt,name=ordering,proto3" json:"ordering,omitempty"`                                        // Ordering field (e.g., 'datetime', '-datetime', 'code')
	Code            string                 `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`                                                // Filter by order code
	Status          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                                            // Filter by status ("n", "p", "e", "c", "r")
	Search          string                 `protobuf:"bytes,7,opt,name=search,proto3" json:"search,omitempty"`                                            // Free text search
	Customer        string                 `protobuf:"bytes,8,opt,name=customer,proto3" json:"customer,omitempty"`                                        // Filter by customer
	Item            int32                  `protobuf:"varint,9,opt,name=item,proto3" json:"item,omitempty"`                                               // Filter by item ID
	Variation       int32                  `protobuf:"varint,10,opt,name=variation,proto3" json:"variation,omitempty"`                                    // Filter by variation ID
	Testmode        bool                   `protobuf:"varint,11,opt,name=testmode,proto3" json:"testmode,omitempty"`                                      // Filter test orders
	RequireApproval bool                   `protobuf:"varint,12,opt,name=require_approval,json=requireApproval,proto3" json:"require_approval,omitempty"` // Filter orders requiring approval
	Email           string                 `protobuf:"bytes,13,opt,name=email,proto3" json:"email,omitempty"`                                             // Filter by email
	Locale          string                 `protobuf:"bytes,14,opt,name=locale,proto3" json:"locale,omitempty"`                                           // Filter by locale
	ModifiedSince   string                 `protobuf:"bytes,15,opt,name=modified_since,json=modifiedSince,proto3" json:"modified_since,omitempty"`        // ISO datetime filter
	CreatedSince    string                 `protobuf:"bytes,16,opt,name=created_since,json=createdSince,proto3" json:"created_since,omitempty"`           // ISO datetime filter
	CreatedBefore   string                 `protobuf:"bytes,17,opt,name=created_before,json=createdBefore,proto3" json:"created_before,omitempty"`        // ISO datetime filter
	SalesChannel    string                 `protobuf:"bytes,18,opt,name=sales_channel,json=salesChannel,proto3" json:"sales_channel,omitempty"`           // Filter by sales channel
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_v1_booking_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_booking_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_v1_booking_order_proto_rawDescGZIP(), []int{0}
}

func (x *ListOrdersRequest) GetOrganizer() string {
	if x != nil {
		return x.Organizer
	}
	return ""
}

func (x *ListOrdersRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *ListOrdersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrdersRequest) GetOrdering() string {
	if x != nil {
		return x.Ordering
	}
	return ""
}

func (x *ListOrdersRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ListOrdersRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListOrdersRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListOrdersRequest) GetCustomer() string {
	if x != nil {
		return x.Customer
	}
	return ""
}

func (x *ListOrdersRequest) GetItem() int32 {
	if x != nil {
		return x.Item
	}
	return 0
}

func (x *ListOrdersRequest) GetVariation() int32 {
	if x != nil {
		return x.Variation
	}
	return 0
}

func (x *ListOrdersRequest) GetTestmode() bool {
	if x != nil {
		return x.Testmode
	}
	return false
}

func (x *ListOrdersRequest) GetRequireApproval() bool {
	if x != nil {
		return x.RequireApproval
	}
	return false
}

func (x *ListOrdersRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ListOrdersRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *ListOrdersRequest) GetModifiedSince() string {
	if x != nil {
		return x.ModifiedSince
	}
	return ""
}

func (x *ListOrdersRequest) GetCreatedSince() string {
	if x != nil {
		return x.CreatedSince
	}
	return ""
}

func (x *ListOrdersRequest) GetCreatedBefore() string {
	if x != nil {
		return x.CreatedBefore
	}
	return ""
}

func (x *ListOrdersRequest) GetSalesChannel() string {
	if x != nil {
		return x.SalesChannel
	}
	return ""
}

// Request: Get single order
type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organizer     string                 `protobuf:"bytes,1,opt,name=organizer,proto3" json:"organizer,omitempty"` // Organizer slug (required)
	Event         string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`         // Event slug (required)
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`           // Order code (required)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_v1_booking_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_booking_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_v1_booking_order_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrderRequest) GetOrganizer() string {
	if x != nil {
		return x.Organizer
	}
	return ""
}

func (x *GetOrderRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *GetOrderRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// Request: Create order
type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organizer     string                 `protobuf:"bytes,1,opt,name=organizer,proto3" json:"organizer,omitempty"`                  // Organizer slug (required)
	Event         string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`                          // Event slug (required)
	OrderData     *OrderCreateData       `protobuf:"bytes,3,opt,name=order_data,json=orderData,proto3" json:"order_data,omitempty"` // Order creation data (required)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_v1_booking_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_booking_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_v1_booking_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderRequest) GetOrganizer() string {
	if x != nil {
		return x.Organizer
	}
	return ""
}

func (x *CreateOrderRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *CreateOrderRequest) GetOrderData() *OrderCreateData {
	if x != nil {
		return x.OrderData
	}
	return nil
}

// Order creation payload
type OrderCreateData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Email          string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`                                                                                                                   // Customer email (required)
	Phone          string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`                                                                                                                   // Customer phone (optional)
	Locale         string                 `protobuf:"bytes,3,opt,name=locale,proto3" json:"locale,omitempty"`                                                                                                                 // Order locale (default: "en")
	Comment        string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`                                                                                                               // Internal comment
	Testmode       bool                   `protobuf:"varint,5,opt,name=testmode,proto3" json:"testmode,omitempty"`                                                                                                            // Test mode order flag
	InvoiceAddress map[string]string      `protobuf:"bytes,6,rep,name=invoice_address,json=invoiceAddress,proto3" json:"invoice_address,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Invoice address fields
	MetaData       map[string]string      `protobuf:"bytes,7,rep,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`                   // Custom metadata
	Positions      []*OrderCreatePosition `protobuf:"bytes,8,rep,name=positions,proto3" json:"positions,omitempty"`                                                                                                           // Order positions (required)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderCreateData) Reset() {
	*x = OrderCreateData{}
	mi := &file_v1_booking_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreateData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreateData) ProtoMessage() {}

func (x *OrderCreateData) ProtoReflect() protoreflect.Message {
	mi := &file_v1_booking_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreateData.ProtoReflect.Descriptor instead.
func (*OrderCreateData) Descriptor() ([]byte, []int) {
	return file_v1_booking_order_proto_rawDescGZIP(), []int{3}
}

func (x *OrderCreateData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *OrderCreateData) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *OrderCreateData) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *OrderCreateData) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *OrderCreateData) GetTestmode() bool {
	if x != nil {
		return x.Testmode
	}
	return false
}

func (x *OrderCreateData) GetInvoiceAddress() map[string]string {
	if x != nil {
		return x.InvoiceAddress
	}
	return nil
}

func (x *OrderCreateData) GetMetaData() map[string]string {
	if x != nil {
		return x.MetaData
	}
	return nil
}

func (x *OrderCreateData) GetPositions() []*OrderCreatePosition {
	if x != nil {
		return x.Positions
	}
	return nil
}

// Position for order creation
type OrderCreatePosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`                      // Item ID (required)
	VariationId   string                 `protobuf:"bytes,2,opt,name=variation_id,json=variationId,proto3" json:"variation_id,omitempty"`       // Variation ID (optional)
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`                               // Quantity (default: 1)
	Price         string                 `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`                                      // Unit price as decimal string (optional)
	AttendeeName  string                 `protobuf:"bytes,5,opt,name=attendee_name,json=attendeeName,proto3" json:"attendee_name,omitempty"`    // Attendee name (optional)
	AttendeeEmail string                 `protobuf:"bytes,6,opt,name=attendee_email,json=attendeeEmail,proto3" json:"attendee_email,omitempty"` // Attendee email (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreatePosition) Reset() {
	*x = OrderCreatePosition{}
	mi := &file_v1_booking_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreatePosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreatePosition) ProtoMessage() {}

func (x *OrderCreatePosition) ProtoReflect() protoreflect.Message {
	mi := &file_v1_booking_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreatePosition.ProtoReflect.Descriptor instead.
func (*OrderCreatePosition) Descriptor() ([]byte, []int) {
	return file_v1_booking_order_proto_rawDescGZIP(), []int{4}
}

func (x *OrderCreatePosition) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *OrderCreatePosition) GetVariationId() string {
	if x != nil {
		return x.VariationId
	}
	return ""
}

func (x *OrderCreatePosition) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderCreatePosition) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *OrderCreatePosition) GetAttendeeName() string {
	if x != nil {
		return x.AttendeeName
	}
	return ""
}

func (x *OrderCreatePosition) GetAttendeeEmail() string {
	if x != nil {
		return x.AttendeeEmail
	}
	return ""
}

// Request: Cancel order
type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organizer     string                 `protobuf:"bytes,1,opt,name=organizer,proto3" json:"organizer,omitempty"` // Organizer slug (required)
	Event         string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`         // Event slug (required)
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`           // Order code (required)
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`     // Cancellation reason (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_v1_booking_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_booking_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_v1_booking_order_proto_rawDescGZIP(), []int{5}
}

func (x *CancelOrderRequest) GetOrganizer() string {
	if x != nil {
		return x.Organizer
	}
	return ""
}

func (x *CancelOrderRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *CancelOrderRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CancelOrderRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

// Request: Approve/mark order as paid
type ApproveOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organizer     string                 `protobuf:"bytes,1,opt,name=organizer,proto3" json:"organizer,omitempty"`                   // Organizer slug (required)
	Event         string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`                           // Event slug (required)
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`                             // Order code (required)
	SendEmail     bool                   `protobuf:"varint,4,opt,name=send_email,json=sendEmail,proto3" json:"send_email,omitempty"` // Send confirmation email (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveOrderRequest) Reset() {
	*x = ApproveOrderRequest{}
	mi := &file_v1_booking_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveOrderRequest) ProtoMessage() {}

func (x *ApproveOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_booking_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveOrderRequest.ProtoReflect.Descriptor instead.
func (*ApproveOrderRequest) Descriptor() ([]byte, []int) {
	return file_v1_booking_order_proto_rawDescGZIP(), []int{6}
}

func (x *ApproveOrderRequest) GetOrganizer() string {
	if x != nil {
		return x.Organizer
	}
	return ""
}

func (x *ApproveOrderRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *ApproveOrderRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ApproveOrderRequest) GetSendEmail() bool {
	if x != nil {
		return x.SendEmail
	}
	return false
}

// Request: Deny order
type DenyOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organizer     string                 `protobuf:"bytes,1,opt,name=organizer,proto3" json:"organizer,omitempty"` // Organizer slug (required)
	Event         string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`         // Event slug (required)
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`           // Order code (required)
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`     // Denial reason (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyOrderRequest) Reset() {
	*x = DenyOrderRequest{}
	mi := &file_v1_booking_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyOrderRequest) ProtoMessage() {}

func (x *DenyOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_booking_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyOrderRequest.ProtoReflect.Descriptor instead.
func (*DenyOrderRequest) Descriptor() ([]byte, []int) {
	return file_v1_booking_order_proto_rawDescGZIP(), []int{7}
}

func (x *DenyOrderRequest) GetOrganizer() string {
	if x != nil {
		return x.Organizer
	}
	return ""
}

func (x *DenyOrderRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *DenyOrderRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DenyOrderRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

// Response: Order list
type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`      // Total count
	Next          string                 `protobuf:"bytes,3,opt,name=next,proto3" json:"next,omitempty"`         // URL for next page
	Previous      string                 `protobuf:"bytes,4,opt,name=previous,proto3" json:"previous,omitempty"` // URL for previous page
	Results       []*Order               `protobuf:"bytes,5,rep,name=results,proto3" json:"results,omitempty"`   // Orders array
	ErrorCode     string                 `protobuf:"bytes,6,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_v1_booking_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_booking_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_v1_booking_order_proto_rawDescGZIP(), []int{8}
}

func (x *ListOrdersResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListOrdersResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListOrdersResponse) GetNext() string {
	if x != nil {
		return x.Next
	}
	return ""
}

func (x *ListOrdersResponse) GetPrevious() string {
	if x != nil {
		return x.Previous
	}
	return ""
}

func (x *ListOrdersResponse) GetResults() []*Order {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ListOrdersResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ListOrdersResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Response: Get single order
type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Order         *Order                 `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_v1_booking_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_booking_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_v1_booking_order_proto_rawDescGZIP(), []int{9}
}

func (x *GetOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *GetOrderResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *GetOrderResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Response: Create order
type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Order         *Order                 `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_v1_booking_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_booking_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_v1_booking_order_proto_rawDescGZIP(), []int{10}
}

func (x *CreateOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *CreateOrderResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *CreateOrderResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Response: Order actions (cancel, approve, deny)
type OrderActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Order         *Order                 `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderActionResponse) Reset() {
	*x = OrderActionResponse{}
	mi := &file_v1_booking_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderActionResponse) ProtoMessage() {}

func (x *OrderActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_booking_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderActionResponse.ProtoReflect.Descriptor instead.
func (*OrderActionResponse) Descriptor() ([]byte, []int) {
	return file_v1_booking_order_proto_rawDescGZIP(), []int{11}
}

func (x *OrderActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OrderActionResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *OrderActionResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *OrderActionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type Order struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identification
	Code   string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`     // Order code (required)
	Event  string `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`   // Event slug (required)
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // Status code: "n"=new, "p"=pending, "e"=expired, "c"=canceled, "r"=refunded
	// Order details
	Testmode     bool   `protobuf:"varint,4,opt,name=testmode,proto3" json:"testmode,omitempty"`                             // Is test order
	Secret       string `protobuf:"bytes,5,opt,name=secret,proto3" json:"secret,omitempty"`                                  // Order secret
	Url          string `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`                                        // Order URL
	Email        string `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`                                    // Customer email
	Phone        string `protobuf:"bytes,8,opt,name=phone,proto3" json:"phone,omitempty"`                                    // Customer phone
	Locale       string `protobuf:"bytes,9,opt,name=locale,proto3" json:"locale,omitempty"`                                  // Order locale
	SalesChannel string `protobuf:"bytes,10,opt,name=sales_channel,json=salesChannel,proto3" json:"sales_channel,omitempty"` // Sales channel
	// Dates
	Datetime     string `protobuf:"bytes,11,opt,name=datetime,proto3" json:"datetime,omitempty"`                             // ISO datetime (created)
	Expires      string `protobuf:"bytes,12,opt,name=expires,proto3" json:"expires,omitempty"`                               // ISO datetime (expiration)
	LastModified string `protobuf:"bytes,13,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"` // ISO datetime (last modified)
	// Financial
	Total string `protobuf:"bytes,14,opt,name=total,proto3" json:"total,omitempty"` // Total as decimal string
	// Related data
	Comment        string            `protobuf:"bytes,15,opt,name=comment,proto3" json:"comment,omitempty"`                                                                                                               // Internal comment
	Positions      []*OrderPosition  `protobuf:"bytes,16,rep,name=positions,proto3" json:"positions,omitempty"`                                                                                                           // Order positions
	Payments       []*OrderPayment   `protobuf:"bytes,17,rep,name=payments,proto3" json:"payments,omitempty"`                                                                                                             // Payments
	Refunds        []*OrderRefund    `protobuf:"bytes,18,rep,name=refunds,proto3" json:"refunds,omitempty"`                                                                                                               // Refunds
	InvoiceAddress map[string]string `protobuf:"bytes,19,rep,name=invoice_address,json=invoiceAddress,proto3" json:"invoice_address,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Invoice address
	MetaData       map[string]string `protobuf:"bytes,20,rep,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`                   // Custom metadata
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_v1_booking_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_v1_booking_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_v1_booking_order_proto_rawDescGZIP(), []int{12}
}

func (x *Order) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Order) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetTestmode() bool {
	if x != nil {
		return x.Testmode
	}
	return false
}

func (x *Order) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *Order) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Order) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Order) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Order) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *Order) GetSalesChannel() string {
	if x != nil {
		return x.SalesChannel
	}
	return ""
}

func (x *Order) GetDatetime() string {
	if x != nil {
		return x.Datetime
	}
	return ""
}

func (x *Order) GetExpires() string {
	if x != nil {
		return x.Expires
	}
	return ""
}

func (x *Order) GetLastModified() string {
	if x != nil {
		return x.LastModified
	}
	return ""
}

func (x *Order) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

func (x *Order) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Order) GetPositions() []*OrderPosition {
	if x != nil {
		return x.Positions
	}
	return nil
}

func (x *Order) GetPayments() []*OrderPayment {
	if x != nil {
		return x.Payments
	}
	return nil
}

func (x *Order) GetRefunds() []*OrderRefund {
	if x != nil {
		return x.Refunds
	}
	return nil
}

func (x *Order) GetInvoiceAddress() map[string]string {
	if x != nil {
		return x.InvoiceAddress
	}
	return nil
}

func (x *Order) GetMetaData() map[string]string {
	if x != nil {
		return x.MetaData
	}
	return nil
}

// Order position
type OrderPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                        // Position ID
	Order         string                 `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`                                   // Order code
	Positionid    int64                  `protobuf:"varint,3,opt,name=positionid,proto3" json:"positionid,omitempty"`                        // Position ID (duplicate for Pretix compat)
	Canceled      bool                   `protobuf:"varint,4,opt,name=canceled,proto3" json:"canceled,omitempty"`                            // Is canceled
	Item          int64                  `protobuf:"varint,5,opt,name=item,proto3" json:"item,omitempty"`                                    // Item ID
	Variation     int64                  `protobuf:"varint,6,opt,name=variation,proto3" json:"variation,omitempty"`                          // Variation ID (optional, use 0 if not set)
	Price         string                 `protobuf:"bytes,7,opt,name=price,proto3" json:"price,omitempty"`                                   // Price as decimal string
	AttendeeName  string                 `protobuf:"bytes,8,opt,name=attendee_name,json=attendeeName,proto3" json:"attendee_name,omitempty"` // Attendee name
	Secret        string                 `protobuf:"bytes,9,opt,name=secret,proto3" json:"secret,omitempty"`                                 // Position secret
	Answers       []*PositionAnswer      `protobuf:"bytes,10,rep,name=answers,proto3" json:"answers,omitempty"`                              // Question answers
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderPosition) Reset() {
	*x = OrderPosition{}
	mi := &file_v1_booking_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPosition) ProtoMessage() {}

func (x *OrderPosition) ProtoReflect() protoreflect.Message {
	mi := &file_v1_booking_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPosition.ProtoReflect.Descriptor instead.
func (*OrderPosition) Descriptor() ([]byte, []int) {
	return file_v1_booking_order_proto_rawDescGZIP(), []int{13}
}

func (x *OrderPosition) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderPosition) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *OrderPosition) GetPositionid() int64 {
	if x != nil {
		return x.Positionid
	}
	return 0
}

func (x *OrderPosition) GetCanceled() bool {
	if x != nil {
		return x.Canceled
	}
	return false
}

func (x *OrderPosition) GetItem() int64 {
	if x != nil {
		return x.Item
	}
	return 0
}

func (x *OrderPosition) GetVariation() int64 {
	if x != nil {
		return x.Variation
	}
	return 0
}

func (x *OrderPosition) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *OrderPosition) GetAttendeeName() string {
	if x != nil {
		return x.AttendeeName
	}
	return ""
}

func (x *OrderPosition) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *OrderPosition) GetAnswers() []*PositionAnswer {
	if x != nil {
		return x.Answers
	}
	return nil
}

// Position answer to a question
type PositionAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    int64                  `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"` // Question ID
	Answer        string                 `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`                            // Answer value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionAnswer) Reset() {
	*x = PositionAnswer{}
	mi := &file_v1_booking_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionAnswer) ProtoMessage() {}

func (x *PositionAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_v1_booking_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionAnswer.ProtoReflect.Descriptor instead.
func (*PositionAnswer) Descriptor() ([]byte, []int) {
	return file_v1_booking_order_proto_rawDescGZIP(), []int{14}
}

func (x *PositionAnswer) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *PositionAnswer) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

// Order payment
type OrderPayment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`            // Payment ID
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"` // Payment provider
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`       // Payment state
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`     // Amount as decimal string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderPayment) Reset() {
	*x = OrderPayment{}
	mi := &file_v1_booking_order_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPayment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPayment) ProtoMessage() {}

func (x *OrderPayment) ProtoReflect() protoreflect.Message {
	mi := &file_v1_booking_order_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPayment.ProtoReflect.Descriptor instead.
func (*OrderPayment) Descriptor() ([]byte, []int) {
	return file_v1_booking_order_proto_rawDescGZIP(), []int{15}
}

func (x *OrderPayment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderPayment) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *OrderPayment) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *OrderPayment) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

// Order refund
type OrderRefund struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`        // Refund ID
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"` // Refund amount as decimal string
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`   // Refund state
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderRefund) Reset() {
	*x = OrderRefund{}
	mi := &file_v1_booking_order_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderRefund) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRefund) ProtoMessage() {}

func (x *OrderRefund) ProtoReflect() protoreflect.Message {
	mi := &file_v1_booking_order_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRefund.ProtoReflect.Descriptor instead.
func (*OrderRefund) Descriptor() ([]byte, []int) {
	return file_v1_booking_order_proto_rawDescGZIP(), []int{16}
}

func (x *OrderRefund) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderRefund) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *OrderRefund) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

var File_v1_booking_order_proto protoreflect.FileDescriptor

const file_v1_booking_order_proto_rawDesc = "" +
	"\n" +
	"\x16v1/booking/order.proto\x12\x11riptik.booking.v1\"\x96\x04\n" +
	"\x11ListOrdersRequest\x12\x1c\n" +
	"\torganizer\x18\x01 \x01(\tR\torganizer\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1a\n" +
	"\bordering\x18\x04 \x01(\tR\bordering\x12\x12\n" +
	"\x04code\x18\x05 \x01(\tR\x04code\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x16\n" +
	"\x06search\x18\a \x01(\tR\x06search\x12\x1a\n" +
	"\bcustomer\x18\b \x01(\tR\bcustomer\x12\x12\n" +
	"\x04item\x18\t \x01(\x05R\x04item\x12\x1c\n" +
	"\tvariation\x18\n" +
	" \x01(\x05R\tvariation\x12\x1a\n" +
	"\btestmode\x18\v \x01(\bR\btestmode\x12)\n" +
	"\x10require_approval\x18\f \x01(\bR\x0frequireApproval\x12\x14\n" +
	"\x05email\x18\r \x01(\tR\x05email\x12\x16\n" +
	"\x06locale\x18\x0e \x01(\tR\x06locale\x12%\n" +
	"\x0emodified_since\x18\x0f \x01(\tR\rmodifiedSince\x12#\n" +
	"\rcreated_since\x18\x10 \x01(\tR\fcreatedSince\x12%\n" +
	"\x0ecreated_before\x18\x11 \x01(\tR\rcreatedBefore\x12#\n" +
	"\rsales_channel\x18\x12 \x01(\tR\fsalesChannel\"Y\n" +
	"\x0fGetOrderRequest\x12\x1c\n" +
	"\torganizer\x18\x01 \x01(\tR\torganizer\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"\x8b\x01\n" +
	"\x12CreateOrderRequest\x12\x1c\n" +
	"\torganizer\x18\x01 \x01(\tR\torganizer\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12A\n" +
	"\n" +
	"order_data\x18\x03 \x01(\v2\".riptik.booking.v1.OrderCreateDataR\torderData\"\x81\x04\n" +
	"\x0fOrderCreateData\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x16\n" +
	"\x06locale\x18\x03 \x01(\tR\x06locale\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\x12\x1a\n" +
	"\btestmode\x18\x05 \x01(\bR\btestmode\x12_\n" +
	"\x0finvoice_address\x18\x06 \x03(\v26.riptik.booking.v1.OrderCreateData.InvoiceAddressEntryR\x0einvoiceAddress\x12M\n" +
	"\tmeta_data\x18\a \x03(\v20.riptik.booking.v1.OrderCreateData.MetaDataEntryR\bmetaData\x12D\n" +
	"\tpositions\x18\b \x03(\v2&.riptik.booking.v1.OrderCreatePositionR\tpositions\x1aA\n" +
	"\x13InvoiceAddressEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetaDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcf\x01\n" +
	"\x13OrderCreatePosition\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12!\n" +
	"\fvariation_id\x18\x02 \x01(\tR\vvariationId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x04 \x01(\tR\x05price\x12#\n" +
	"\rattendee_name\x18\x05 \x01(\tR\fattendeeName\x12%\n" +
	"\x0eattendee_email\x18\x06 \x01(\tR\rattendeeEmail\"v\n" +
	"\x12CancelOrderRequest\x12\x1c\n" +
	"\torganizer\x18\x01 \x01(\tR\torganizer\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\"|\n" +
	"\x13ApproveOrderRequest\x12\x1c\n" +
	"\torganizer\x18\x01 \x01(\tR\torganizer\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x1d\n" +
	"\n" +
	"send_email\x18\x04 \x01(\bR\tsendEmail\"t\n" +
	"\x10DenyOrderRequest\x12\x1c\n" +
	"\torganizer\x18\x01 \x01(\tR\torganizer\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\"\xec\x01\n" +
	"\x12ListOrdersResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x12\n" +
	"\x04next\x18\x03 \x01(\tR\x04next\x12\x1a\n" +
	"\bprevious\x18\x04 \x01(\tR\bprevious\x122\n" +
	"\aresults\x18\x05 \x03(\v2\x18.riptik.booking.v1.OrderR\aresults\x12\x1d\n" +
	"\n" +
	"error_code\x18\x06 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\"\xa0\x01\n" +
	"\x10GetOrderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12.\n" +
	"\x05order\x18\x02 \x01(\v2\x18.riptik.booking.v1.OrderR\x05order\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\xa3\x01\n" +
	"\x13CreateOrderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12.\n" +
	"\x05order\x18\x02 \x01(\v2\x18.riptik.booking.v1.OrderR\x05order\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\xa3\x01\n" +
	"\x13OrderActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12.\n" +
	"\x05order\x18\x02 \x01(\v2\x18.riptik.booking.v1.OrderR\x05order\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\xd6\x06\n" +
	"\x05Order\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1a\n" +
	"\btestmode\x18\x04 \x01(\bR\btestmode\x12\x16\n" +
	"\x06secret\x18\x05 \x01(\tR\x06secret\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\b \x01(\tR\x05phone\x12\x16\n" +
	"\x06locale\x18\t \x01(\tR\x06locale\x12#\n" +
	"\rsales_channel\x18\n" +
	" \x01(\tR\fsalesChannel\x12\x1a\n" +
	"\bdatetime\x18\v \x01(\tR\bdatetime\x12\x18\n" +
	"\aexpires\x18\f \x01(\tR\aexpires\x12#\n" +
	"\rlast_modified\x18\r \x01(\tR\flastModified\x12\x14\n" +
	"\x05total\x18\x0e \x01(\tR\x05total\x12\x18\n" +
	"\acomment\x18\x0f \x01(\tR\acomment\x12>\n" +
	"\tpositions\x18\x10 \x03(\v2 .riptik.booking.v1.OrderPositionR\tpositions\x12;\n" +
	"\bpayments\x18\x11 \x03(\v2\x1f.riptik.booking.v1.OrderPaymentR\bpayments\x128\n" +
	"\arefunds\x18\x12 \x03(\v2\x1e.riptik.booking.v1.OrderRefundR\arefunds\x12U\n" +
	"\x0finvoice_address\x18\x13 \x03(\v2,.riptik.booking.v1.Order.InvoiceAddressEntryR\x0einvoiceAddress\x12C\n" +
	"\tmeta_data\x18\x14 \x03(\v2&.riptik.booking.v1.Order.MetaDataEntryR\bmetaData\x1aA\n" +
	"\x13InvoiceAddressEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetaDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb3\x02\n" +
	"\rOrderPosition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05order\x18\x02 \x01(\tR\x05order\x12\x1e\n" +
	"\n" +
	"positionid\x18\x03 \x01(\x03R\n" +
	"positionid\x12\x1a\n" +
	"\bcanceled\x18\x04 \x01(\bR\bcanceled\x12\x12\n" +
	"\x04item\x18\x05 \x01(\x03R\x04item\x12\x1c\n" +
	"\tvariation\x18\x06 \x01(\x03R\tvariation\x12\x14\n" +
	"\x05price\x18\a \x01(\tR\x05price\x12#\n" +
	"\rattendee_name\x18\b \x01(\tR\fattendeeName\x12\x16\n" +
	"\x06secret\x18\t \x01(\tR\x06secret\x12;\n" +
	"\aanswers\x18\n" +
	" \x03(\v2!.riptik.booking.v1.PositionAnswerR\aanswers\"I\n" +
	"\x0ePositionAnswer\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\x03R\n" +
	"questionId\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\tR\x06answer\"h\n" +
	"\fOrderPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\"K\n" +
	"\vOrderRefund\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05stateB*Z(github.com/riptik/services/pb/v1/bookingb\x06proto3"

var (
	file_v1_booking_order_proto_rawDescOnce sync.Once
	file_v1_booking_order_proto_rawDescData []byte
)

func file_v1_booking_order_proto_rawDescGZIP() []byte {
	file_v1_booking_order_proto_rawDescOnce.Do(func() {
		file_v1_booking_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_booking_order_proto_rawDesc), len(file_v1_booking_order_proto_rawDesc)))
	})
	return file_v1_booking_order_proto_rawDescData
}

var file_v1_booking_order_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_v1_booking_order_proto_goTypes = []any{
	(*ListOrdersRequest)(nil),   // 0: riptik.booking.v1.ListOrdersRequest
	(*GetOrderRequest)(nil),     // 1: riptik.booking.v1.GetOrderRequest
	(*CreateOrderRequest)(nil),  // 2: riptik.booking.v1.CreateOrderRequest
	(*OrderCreateData)(nil),     // 3: riptik.booking.v1.OrderCreateData
	(*OrderCreatePosition)(nil), // 4: riptik.booking.v1.OrderCreatePosition
	(*CancelOrderRequest)(nil),  // 5: riptik.booking.v1.CancelOrderRequest
	(*ApproveOrderRequest)(nil), // 6: riptik.booking.v1.ApproveOrderRequest
	(*DenyOrderRequest)(nil),    // 7: riptik.booking.v1.DenyOrderRequest
	(*ListOrdersResponse)(nil),  // 8: riptik.booking.v1.ListOrdersResponse
	(*GetOrderResponse)(nil),    // 9: riptik.booking.v1.GetOrderResponse
	(*CreateOrderResponse)(nil), // 10: riptik.booking.v1.CreateOrderResponse
	(*OrderActionResponse)(nil), // 11: riptik.booking.v1.OrderActionResponse
	(*Order)(nil),               // 12: riptik.booking.v1.Order
	(*OrderPosition)(nil),       // 13: riptik.booking.v1.OrderPosition
	(*PositionAnswer)(nil),      // 14: riptik.booking.v1.PositionAnswer
	(*OrderPayment)(nil),        // 15: riptik.booking.v1.OrderPayment
	(*OrderRefund)(nil),         // 16: riptik.booking.v1.OrderRefund
	nil,                         // 17: riptik.booking.v1.OrderCreateData.InvoiceAddressEntry
	nil,                         // 18: riptik.booking.v1.OrderCreateData.MetaDataEntry
	nil,                         // 19: riptik.booking.v1.Order.InvoiceAddressEntry
	nil,                         // 20: riptik.booking.v1.Order.MetaDataEntry
}
var file_v1_booking_order_proto_depIdxs = []int32{
	3,  // 0: riptik.booking.v1.CreateOrderRequest.order_data:type_name -> riptik.booking.v1.OrderCreateData
	17, // 1: riptik.booking.v1.OrderCreateData.invoice_address:type_name -> riptik.booking.v1.OrderCreateData.InvoiceAddressEntry
	18, // 2: riptik.booking.v1.OrderCreateData.meta_data:type_name -> riptik.booking.v1.OrderCreateData.MetaDataEntry
	4,  // 3: riptik.booking.v1.OrderCreateData.positions:type_name -> riptik.booking.v1.OrderCreatePosition
	12, // 4: riptik.booking.v1.ListOrdersResponse.results:type_name -> riptik.booking.v1.Order
	12, // 5: riptik.booking.v1.GetOrderResponse.order:type_name -> riptik.booking.v1.Order
	12, // 6: riptik.booking.v1.CreateOrderResponse.order:type_name -> riptik.booking.v1.Order
	12, // 7: riptik.booking.v1.OrderActionResponse.order:type_name -> riptik.booking.v1.Order
	13, // 8: riptik.booking.v1.Order.positions:type_name -> riptik.booking.v1.OrderPosition
	15, // 9: riptik.booking.v1.Order.payments:type_name -> riptik.booking.v1.OrderPayment
	16, // 10: riptik.booking.v1.Order.refunds:type_name -> riptik.booking.v1.OrderRefund
	19, // 11: riptik.booking.v1.Order.invoice_address:type_name -> riptik.booking.v1.Order.InvoiceAddressEntry
	20, // 12: riptik.booking.v1.Order.meta_data:type_name -> riptik.booking.v1.Order.MetaDataEntry
	14, // 13: riptik.booking.v1.OrderPosition.answers:type_name -> riptik.booking.v1.PositionAnswer
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_v1_booking_order_proto_init() }
func file_v1_booking_order_proto_init() {
	if File_v1_booking_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_booking_order_proto_rawDesc), len(file_v1_booking_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_booking_order_proto_goTypes,
		DependencyIndexes: file_v1_booking_order_proto_depIdxs,
		MessageInfos:      file_v1_booking_order_proto_msgTypes,
	}.Build()
	File_v1_booking_order_proto = out.File
	file_v1_booking_order_proto_goTypes = nil
	file_v1_booking_order_proto_depIdxs = nil
}
