// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: v1/audit/audit.proto

package audit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Domain model: AuditLogEntry
type AuditLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	ObjectId      string                 `protobuf:"bytes,3,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	ActionType    string                 `protobuf:"bytes,4,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                                              // Optional
	OldData       map[string]string      `protobuf:"bytes,6,rep,name=old_data,json=oldData,proto3" json:"old_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // JSON-compatible key-value pairs
	NewData       map[string]string      `protobuf:"bytes,7,rep,name=new_data,json=newData,proto3" json:"new_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // JSON-compatible key-value pairs
	Source        string                 `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"`
	Severity      string                 `protobuf:"bytes,9,opt,name=severity,proto3" json:"severity,omitempty"`
	Timestamp     string                 `protobuf:"bytes,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // ISO datetime string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogEntry) Reset() {
	*x = AuditLogEntry{}
	mi := &file_v1_audit_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogEntry) ProtoMessage() {}

func (x *AuditLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_v1_audit_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogEntry.ProtoReflect.Descriptor instead.
func (*AuditLogEntry) Descriptor() ([]byte, []int) {
	return file_v1_audit_audit_proto_rawDescGZIP(), []int{0}
}

func (x *AuditLogEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditLogEntry) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *AuditLogEntry) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *AuditLogEntry) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *AuditLogEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuditLogEntry) GetOldData() map[string]string {
	if x != nil {
		return x.OldData
	}
	return nil
}

func (x *AuditLogEntry) GetNewData() map[string]string {
	if x != nil {
		return x.NewData
	}
	return nil
}

func (x *AuditLogEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AuditLogEntry) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *AuditLogEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// Context information for audit logs
type AuditContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *ContextUser           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Event         *ContextEvent          `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	Organization  *ContextOrganization   `protobuf:"bytes,3,opt,name=organization,proto3" json:"organization,omitempty"`
	Device        *ContextDevice         `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`
	ApiToken      *ContextAPIToken       `protobuf:"bytes,5,opt,name=api_token,json=apiToken,proto3" json:"api_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditContext) Reset() {
	*x = AuditContext{}
	mi := &file_v1_audit_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditContext) ProtoMessage() {}

func (x *AuditContext) ProtoReflect() protoreflect.Message {
	mi := &file_v1_audit_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditContext.ProtoReflect.Descriptor instead.
func (*AuditContext) Descriptor() ([]byte, []int) {
	return file_v1_audit_audit_proto_rawDescGZIP(), []int{1}
}

func (x *AuditContext) GetUser() *ContextUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *AuditContext) GetEvent() *ContextEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *AuditContext) GetOrganization() *ContextOrganization {
	if x != nil {
		return x.Organization
	}
	return nil
}

func (x *AuditContext) GetDevice() *ContextDevice {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *AuditContext) GetApiToken() *ContextAPIToken {
	if x != nil {
		return x.ApiToken
	}
	return nil
}

type ContextUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextUser) Reset() {
	*x = ContextUser{}
	mi := &file_v1_audit_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextUser) ProtoMessage() {}

func (x *ContextUser) ProtoReflect() protoreflect.Message {
	mi := &file_v1_audit_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextUser.ProtoReflect.Descriptor instead.
func (*ContextUser) Descriptor() ([]byte, []int) {
	return file_v1_audit_audit_proto_rawDescGZIP(), []int{2}
}

func (x *ContextUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContextUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ContextEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextEvent) Reset() {
	*x = ContextEvent{}
	mi := &file_v1_audit_audit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextEvent) ProtoMessage() {}

func (x *ContextEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_audit_audit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextEvent.ProtoReflect.Descriptor instead.
func (*ContextEvent) Descriptor() ([]byte, []int) {
	return file_v1_audit_audit_proto_rawDescGZIP(), []int{3}
}

func (x *ContextEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContextEvent) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type ContextOrganization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextOrganization) Reset() {
	*x = ContextOrganization{}
	mi := &file_v1_audit_audit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextOrganization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextOrganization) ProtoMessage() {}

func (x *ContextOrganization) ProtoReflect() protoreflect.Message {
	mi := &file_v1_audit_audit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextOrganization.ProtoReflect.Descriptor instead.
func (*ContextOrganization) Descriptor() ([]byte, []int) {
	return file_v1_audit_audit_proto_rawDescGZIP(), []int{4}
}

func (x *ContextOrganization) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContextOrganization) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type ContextDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextDevice) Reset() {
	*x = ContextDevice{}
	mi := &file_v1_audit_audit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextDevice) ProtoMessage() {}

func (x *ContextDevice) ProtoReflect() protoreflect.Message {
	mi := &file_v1_audit_audit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextDevice.ProtoReflect.Descriptor instead.
func (*ContextDevice) Descriptor() ([]byte, []int) {
	return file_v1_audit_audit_proto_rawDescGZIP(), []int{5}
}

func (x *ContextDevice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContextDevice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ContextAPIToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextAPIToken) Reset() {
	*x = ContextAPIToken{}
	mi := &file_v1_audit_audit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextAPIToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextAPIToken) ProtoMessage() {}

func (x *ContextAPIToken) ProtoReflect() protoreflect.Message {
	mi := &file_v1_audit_audit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextAPIToken.ProtoReflect.Descriptor instead.
func (*ContextAPIToken) Descriptor() ([]byte, []int) {
	return file_v1_audit_audit_proto_rawDescGZIP(), []int{6}
}

func (x *ContextAPIToken) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContextAPIToken) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Requests
type CreateAuditLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentType   string                 `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`                                          // Required (e.g., "order", "event")
	ObjectId      string                 `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`                                                   // Required (e.g., order ID)
	ActionType    string                 `protobuf:"bytes,3,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`                                             // Required (e.g., "create", "update", "delete")
	Data          map[string]string      `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional data as key-value pairs
	Context       *AuditContext          `protobuf:"bytes,5,opt,name=context,proto3" json:"context,omitempty"`                                                                     // Optional context information
	Severity      string                 `protobuf:"bytes,6,opt,name=severity,proto3" json:"severity,omitempty"`                                                                   // Optional (e.g., "info", "warning", "error")
	Source        string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`                                                                       // Optional (e.g., "api", "webhook", "manual")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuditLogRequest) Reset() {
	*x = CreateAuditLogRequest{}
	mi := &file_v1_audit_audit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuditLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuditLogRequest) ProtoMessage() {}

func (x *CreateAuditLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_audit_audit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuditLogRequest.ProtoReflect.Descriptor instead.
func (*CreateAuditLogRequest) Descriptor() ([]byte, []int) {
	return file_v1_audit_audit_proto_rawDescGZIP(), []int{7}
}

func (x *CreateAuditLogRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *CreateAuditLogRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *CreateAuditLogRequest) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *CreateAuditLogRequest) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CreateAuditLogRequest) GetContext() *AuditContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CreateAuditLogRequest) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *CreateAuditLogRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type QueryAuditLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentType   string                 `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // Optional filter
	ObjectId      string                 `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`          // Optional filter
	ActionType    string                 `protobuf:"bytes,3,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`    // Optional filter
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                // Optional filter
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`                              // Optional filter
	Severity      string                 `protobuf:"bytes,6,opt,name=severity,proto3" json:"severity,omitempty"`                          // Optional filter
	StartDate     string                 `protobuf:"bytes,7,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`       // Optional ISO datetime string
	EndDate       string                 `protobuf:"bytes,8,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`             // Optional ISO datetime string
	Page          int32                  `protobuf:"varint,9,opt,name=page,proto3" json:"page,omitempty"`                                 // Defaults to 1
	Limit         int32                  `protobuf:"varint,10,opt,name=limit,proto3" json:"limit,omitempty"`                              // Defaults to 25, max 100
	SortOrder     string                 `protobuf:"bytes,11,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`      // "asc" or "desc", defaults to "desc"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAuditLogsRequest) Reset() {
	*x = QueryAuditLogsRequest{}
	mi := &file_v1_audit_audit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAuditLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAuditLogsRequest) ProtoMessage() {}

func (x *QueryAuditLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_audit_audit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAuditLogsRequest.ProtoReflect.Descriptor instead.
func (*QueryAuditLogsRequest) Descriptor() ([]byte, []int) {
	return file_v1_audit_audit_proto_rawDescGZIP(), []int{8}
}

func (x *QueryAuditLogsRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *QueryAuditLogsRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *QueryAuditLogsRequest) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *QueryAuditLogsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *QueryAuditLogsRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *QueryAuditLogsRequest) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *QueryAuditLogsRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *QueryAuditLogsRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *QueryAuditLogsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *QueryAuditLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryAuditLogsRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

type GetAuditLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditLogRequest) Reset() {
	*x = GetAuditLogRequest{}
	mi := &file_v1_audit_audit_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditLogRequest) ProtoMessage() {}

func (x *GetAuditLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_audit_audit_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditLogRequest.ProtoReflect.Descriptor instead.
func (*GetAuditLogRequest) Descriptor() ([]byte, []int) {
	return file_v1_audit_audit_proto_rawDescGZIP(), []int{9}
}

func (x *GetAuditLogRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AuditLogSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentType   string                 `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // Optional filter
	Days          int32                  `protobuf:"varint,2,opt,name=days,proto3" json:"days,omitempty"`                                 // Defaults to 30, valid range 1-365
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogSummaryRequest) Reset() {
	*x = AuditLogSummaryRequest{}
	mi := &file_v1_audit_audit_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogSummaryRequest) ProtoMessage() {}

func (x *AuditLogSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_audit_audit_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogSummaryRequest.ProtoReflect.Descriptor instead.
func (*AuditLogSummaryRequest) Descriptor() ([]byte, []int) {
	return file_v1_audit_audit_proto_rawDescGZIP(), []int{10}
}

func (x *AuditLogSummaryRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *AuditLogSummaryRequest) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

type AuditTrailRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContentType    string                 `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`           // Required
	ObjectId       string                 `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`                    // Required
	Limit          int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                                         // Defaults to 25, max 100
	IncludeRelated bool                   `protobuf:"varint,4,opt,name=include_related,json=includeRelated,proto3" json:"include_related,omitempty"` // Optional
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuditTrailRequest) Reset() {
	*x = AuditTrailRequest{}
	mi := &file_v1_audit_audit_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditTrailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditTrailRequest) ProtoMessage() {}

func (x *AuditTrailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_audit_audit_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditTrailRequest.ProtoReflect.Descriptor instead.
func (*AuditTrailRequest) Descriptor() ([]byte, []int) {
	return file_v1_audit_audit_proto_rawDescGZIP(), []int{11}
}

func (x *AuditTrailRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *AuditTrailRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *AuditTrailRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *AuditTrailRequest) GetIncludeRelated() bool {
	if x != nil {
		return x.IncludeRelated
	}
	return false
}

type CleanupAuditLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetentionDays int32                  `protobuf:"varint,1,opt,name=retention_days,json=retentionDays,proto3" json:"retention_days,omitempty"` // Required, minimum 1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupAuditLogsRequest) Reset() {
	*x = CleanupAuditLogsRequest{}
	mi := &file_v1_audit_audit_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupAuditLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupAuditLogsRequest) ProtoMessage() {}

func (x *CleanupAuditLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_audit_audit_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupAuditLogsRequest.ProtoReflect.Descriptor instead.
func (*CleanupAuditLogsRequest) Descriptor() ([]byte, []int) {
	return file_v1_audit_audit_proto_rawDescGZIP(), []int{12}
}

func (x *CleanupAuditLogsRequest) GetRetentionDays() int32 {
	if x != nil {
		return x.RetentionDays
	}
	return 0
}

// Response pagination metadata
type PaginationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationInfo) Reset() {
	*x = PaginationInfo{}
	mi := &file_v1_audit_audit_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationInfo) ProtoMessage() {}

func (x *PaginationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_audit_audit_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationInfo.ProtoReflect.Descriptor instead.
func (*PaginationInfo) Descriptor() ([]byte, []int) {
	return file_v1_audit_audit_proto_rawDescGZIP(), []int{13}
}

func (x *PaginationInfo) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationInfo) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PaginationInfo) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PaginationInfo) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

// Summary entry
type AuditSummaryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionType    string                 `protobuf:"bytes,1,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditSummaryEntry) Reset() {
	*x = AuditSummaryEntry{}
	mi := &file_v1_audit_audit_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditSummaryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditSummaryEntry) ProtoMessage() {}

func (x *AuditSummaryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_v1_audit_audit_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditSummaryEntry.ProtoReflect.Descriptor instead.
func (*AuditSummaryEntry) Descriptor() ([]byte, []int) {
	return file_v1_audit_audit_proto_rawDescGZIP(), []int{14}
}

func (x *AuditSummaryEntry) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *AuditSummaryEntry) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *AuditSummaryEntry) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Responses
type CreateAuditLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Entry         *AuditLogEntry         `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuditLogResponse) Reset() {
	*x = CreateAuditLogResponse{}
	mi := &file_v1_audit_audit_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuditLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuditLogResponse) ProtoMessage() {}

func (x *CreateAuditLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_audit_audit_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuditLogResponse.ProtoReflect.Descriptor instead.
func (*CreateAuditLogResponse) Descriptor() ([]byte, []int) {
	return file_v1_audit_audit_proto_rawDescGZIP(), []int{15}
}

func (x *CreateAuditLogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateAuditLogResponse) GetEntry() *AuditLogEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type QueryAuditLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Entries       []*AuditLogEntry       `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	Pagination    *PaginationInfo        `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAuditLogsResponse) Reset() {
	*x = QueryAuditLogsResponse{}
	mi := &file_v1_audit_audit_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAuditLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAuditLogsResponse) ProtoMessage() {}

func (x *QueryAuditLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_audit_audit_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAuditLogsResponse.ProtoReflect.Descriptor instead.
func (*QueryAuditLogsResponse) Descriptor() ([]byte, []int) {
	return file_v1_audit_audit_proto_rawDescGZIP(), []int{16}
}

func (x *QueryAuditLogsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *QueryAuditLogsResponse) GetEntries() []*AuditLogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *QueryAuditLogsResponse) GetPagination() *PaginationInfo {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetAuditLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Entry         *AuditLogEntry         `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditLogResponse) Reset() {
	*x = GetAuditLogResponse{}
	mi := &file_v1_audit_audit_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditLogResponse) ProtoMessage() {}

func (x *GetAuditLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_audit_audit_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditLogResponse.ProtoReflect.Descriptor instead.
func (*GetAuditLogResponse) Descriptor() ([]byte, []int) {
	return file_v1_audit_audit_proto_rawDescGZIP(), []int{17}
}

func (x *GetAuditLogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetAuditLogResponse) GetEntry() *AuditLogEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type AuditLogSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Summary       []*AuditSummaryEntry   `protobuf:"bytes,2,rep,name=summary,proto3" json:"summary,omitempty"`
	Period        string                 `protobuf:"bytes,3,opt,name=period,proto3" json:"period,omitempty"`                        // e.g., "Last 30 days"
	StartDate     string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // ISO datetime string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogSummaryResponse) Reset() {
	*x = AuditLogSummaryResponse{}
	mi := &file_v1_audit_audit_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogSummaryResponse) ProtoMessage() {}

func (x *AuditLogSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_audit_audit_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogSummaryResponse.ProtoReflect.Descriptor instead.
func (*AuditLogSummaryResponse) Descriptor() ([]byte, []int) {
	return file_v1_audit_audit_proto_rawDescGZIP(), []int{18}
}

func (x *AuditLogSummaryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuditLogSummaryResponse) GetSummary() []*AuditSummaryEntry {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *AuditLogSummaryResponse) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *AuditLogSummaryResponse) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

type AuditTrailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	ObjectId      string                 `protobuf:"bytes,3,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Trail         []*AuditLogEntry       `protobuf:"bytes,4,rep,name=trail,proto3" json:"trail,omitempty"`
	TotalEvents   int32                  `protobuf:"varint,5,opt,name=total_events,json=totalEvents,proto3" json:"total_events,omitempty"`
	HasMore       bool                   `protobuf:"varint,6,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditTrailResponse) Reset() {
	*x = AuditTrailResponse{}
	mi := &file_v1_audit_audit_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditTrailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditTrailResponse) ProtoMessage() {}

func (x *AuditTrailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_audit_audit_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditTrailResponse.ProtoReflect.Descriptor instead.
func (*AuditTrailResponse) Descriptor() ([]byte, []int) {
	return file_v1_audit_audit_proto_rawDescGZIP(), []int{19}
}

func (x *AuditTrailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuditTrailResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *AuditTrailResponse) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *AuditTrailResponse) GetTrail() []*AuditLogEntry {
	if x != nil {
		return x.Trail
	}
	return nil
}

func (x *AuditTrailResponse) GetTotalEvents() int32 {
	if x != nil {
		return x.TotalEvents
	}
	return 0
}

func (x *AuditTrailResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type CleanupAuditLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DeletedCount  int32                  `protobuf:"varint,3,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupAuditLogsResponse) Reset() {
	*x = CleanupAuditLogsResponse{}
	mi := &file_v1_audit_audit_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupAuditLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupAuditLogsResponse) ProtoMessage() {}

func (x *CleanupAuditLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_audit_audit_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupAuditLogsResponse.ProtoReflect.Descriptor instead.
func (*CleanupAuditLogsResponse) Descriptor() ([]byte, []int) {
	return file_v1_audit_audit_proto_rawDescGZIP(), []int{20}
}

func (x *CleanupAuditLogsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CleanupAuditLogsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CleanupAuditLogsResponse) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

var File_v1_audit_audit_proto protoreflect.FileDescriptor

const file_v1_audit_audit_proto_rawDesc = "" +
	"\n" +
	"\x14v1/audit/audit.proto\x12\x0friptik.audit.v1\"\xf3\x03\n" +
	"\rAuditLogEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x1b\n" +
	"\tobject_id\x18\x03 \x01(\tR\bobjectId\x12\x1f\n" +
	"\vaction_type\x18\x04 \x01(\tR\n" +
	"actionType\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\x12F\n" +
	"\bold_data\x18\x06 \x03(\v2+.riptik.audit.v1.AuditLogEntry.OldDataEntryR\aoldData\x12F\n" +
	"\bnew_data\x18\a \x03(\v2+.riptik.audit.v1.AuditLogEntry.NewDataEntryR\anewData\x12\x16\n" +
	"\x06source\x18\b \x01(\tR\x06source\x12\x1a\n" +
	"\bseverity\x18\t \x01(\tR\bseverity\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\tR\ttimestamp\x1a:\n" +
	"\fOldDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fNewDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb6\x02\n" +
	"\fAuditContext\x120\n" +
	"\x04user\x18\x01 \x01(\v2\x1c.riptik.audit.v1.ContextUserR\x04user\x123\n" +
	"\x05event\x18\x02 \x01(\v2\x1d.riptik.audit.v1.ContextEventR\x05event\x12H\n" +
	"\forganization\x18\x03 \x01(\v2$.riptik.audit.v1.ContextOrganizationR\forganization\x126\n" +
	"\x06device\x18\x04 \x01(\v2\x1e.riptik.audit.v1.ContextDeviceR\x06device\x12=\n" +
	"\tapi_token\x18\x05 \x01(\v2 .riptik.audit.v1.ContextAPITokenR\bapiToken\"1\n" +
	"\vContextUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"2\n" +
	"\fContextEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\"9\n" +
	"\x13ContextOrganization\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\"3\n" +
	"\rContextDevice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"5\n" +
	"\x0fContextAPIToken\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xe4\x02\n" +
	"\x15CreateAuditLogRequest\x12!\n" +
	"\fcontent_type\x18\x01 \x01(\tR\vcontentType\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\tR\bobjectId\x12\x1f\n" +
	"\vaction_type\x18\x03 \x01(\tR\n" +
	"actionType\x12D\n" +
	"\x04data\x18\x04 \x03(\v20.riptik.audit.v1.CreateAuditLogRequest.DataEntryR\x04data\x127\n" +
	"\acontext\x18\x05 \x01(\v2\x1d.riptik.audit.v1.AuditContextR\acontext\x12\x1a\n" +
	"\bseverity\x18\x06 \x01(\tR\bseverity\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc8\x02\n" +
	"\x15QueryAuditLogsRequest\x12!\n" +
	"\fcontent_type\x18\x01 \x01(\tR\vcontentType\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\tR\bobjectId\x12\x1f\n" +
	"\vaction_type\x18\x03 \x01(\tR\n" +
	"actionType\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x1a\n" +
	"\bseverity\x18\x06 \x01(\tR\bseverity\x12\x1d\n" +
	"\n" +
	"start_date\x18\a \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\b \x01(\tR\aendDate\x12\x12\n" +
	"\x04page\x18\t \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\n" +
	" \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"sort_order\x18\v \x01(\tR\tsortOrder\"$\n" +
	"\x12GetAuditLogRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"O\n" +
	"\x16AuditLogSummaryRequest\x12!\n" +
	"\fcontent_type\x18\x01 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04days\x18\x02 \x01(\x05R\x04days\"\x92\x01\n" +
	"\x11AuditTrailRequest\x12!\n" +
	"\fcontent_type\x18\x01 \x01(\tR\vcontentType\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\tR\bobjectId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12'\n" +
	"\x0finclude_related\x18\x04 \x01(\bR\x0eincludeRelated\"@\n" +
	"\x17CleanupAuditLogsRequest\x12%\n" +
	"\x0eretention_days\x18\x01 \x01(\x05R\rretentionDays\"q\n" +
	"\x0ePaginationInfo\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"f\n" +
	"\x11AuditSummaryEntry\x12\x1f\n" +
	"\vaction_type\x18\x01 \x01(\tR\n" +
	"actionType\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"h\n" +
	"\x16CreateAuditLogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x124\n" +
	"\x05entry\x18\x02 \x01(\v2\x1e.riptik.audit.v1.AuditLogEntryR\x05entry\"\xad\x01\n" +
	"\x16QueryAuditLogsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x128\n" +
	"\aentries\x18\x02 \x03(\v2\x1e.riptik.audit.v1.AuditLogEntryR\aentries\x12?\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x1f.riptik.audit.v1.PaginationInfoR\n" +
	"pagination\"e\n" +
	"\x13GetAuditLogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x124\n" +
	"\x05entry\x18\x02 \x01(\v2\x1e.riptik.audit.v1.AuditLogEntryR\x05entry\"\xa8\x01\n" +
	"\x17AuditLogSummaryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12<\n" +
	"\asummary\x18\x02 \x03(\v2\".riptik.audit.v1.AuditSummaryEntryR\asummary\x12\x16\n" +
	"\x06period\x18\x03 \x01(\tR\x06period\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\"\xe2\x01\n" +
	"\x12AuditTrailResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x1b\n" +
	"\tobject_id\x18\x03 \x01(\tR\bobjectId\x124\n" +
	"\x05trail\x18\x04 \x03(\v2\x1e.riptik.audit.v1.AuditLogEntryR\x05trail\x12!\n" +
	"\ftotal_events\x18\x05 \x01(\x05R\vtotalEvents\x12\x19\n" +
	"\bhas_more\x18\x06 \x01(\bR\ahasMore\"s\n" +
	"\x18CleanupAuditLogsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rdeleted_count\x18\x03 \x01(\x05R\fdeletedCountB(Z&github.com/riptik/services/pb/v1/auditb\x06proto3"

var (
	file_v1_audit_audit_proto_rawDescOnce sync.Once
	file_v1_audit_audit_proto_rawDescData []byte
)

func file_v1_audit_audit_proto_rawDescGZIP() []byte {
	file_v1_audit_audit_proto_rawDescOnce.Do(func() {
		file_v1_audit_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_audit_audit_proto_rawDesc), len(file_v1_audit_audit_proto_rawDesc)))
	})
	return file_v1_audit_audit_proto_rawDescData
}

var file_v1_audit_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_v1_audit_audit_proto_goTypes = []any{
	(*AuditLogEntry)(nil),            // 0: riptik.audit.v1.AuditLogEntry
	(*AuditContext)(nil),             // 1: riptik.audit.v1.AuditContext
	(*ContextUser)(nil),              // 2: riptik.audit.v1.ContextUser
	(*ContextEvent)(nil),             // 3: riptik.audit.v1.ContextEvent
	(*ContextOrganization)(nil),      // 4: riptik.audit.v1.ContextOrganization
	(*ContextDevice)(nil),            // 5: riptik.audit.v1.ContextDevice
	(*ContextAPIToken)(nil),          // 6: riptik.audit.v1.ContextAPIToken
	(*CreateAuditLogRequest)(nil),    // 7: riptik.audit.v1.CreateAuditLogRequest
	(*QueryAuditLogsRequest)(nil),    // 8: riptik.audit.v1.QueryAuditLogsRequest
	(*GetAuditLogRequest)(nil),       // 9: riptik.audit.v1.GetAuditLogRequest
	(*AuditLogSummaryRequest)(nil),   // 10: riptik.audit.v1.AuditLogSummaryRequest
	(*AuditTrailRequest)(nil),        // 11: riptik.audit.v1.AuditTrailRequest
	(*CleanupAuditLogsRequest)(nil),  // 12: riptik.audit.v1.CleanupAuditLogsRequest
	(*PaginationInfo)(nil),           // 13: riptik.audit.v1.PaginationInfo
	(*AuditSummaryEntry)(nil),        // 14: riptik.audit.v1.AuditSummaryEntry
	(*CreateAuditLogResponse)(nil),   // 15: riptik.audit.v1.CreateAuditLogResponse
	(*QueryAuditLogsResponse)(nil),   // 16: riptik.audit.v1.QueryAuditLogsResponse
	(*GetAuditLogResponse)(nil),      // 17: riptik.audit.v1.GetAuditLogResponse
	(*AuditLogSummaryResponse)(nil),  // 18: riptik.audit.v1.AuditLogSummaryResponse
	(*AuditTrailResponse)(nil),       // 19: riptik.audit.v1.AuditTrailResponse
	(*CleanupAuditLogsResponse)(nil), // 20: riptik.audit.v1.CleanupAuditLogsResponse
	nil,                              // 21: riptik.audit.v1.AuditLogEntry.OldDataEntry
	nil,                              // 22: riptik.audit.v1.AuditLogEntry.NewDataEntry
	nil,                              // 23: riptik.audit.v1.CreateAuditLogRequest.DataEntry
}
var file_v1_audit_audit_proto_depIdxs = []int32{
	21, // 0: riptik.audit.v1.AuditLogEntry.old_data:type_name -> riptik.audit.v1.AuditLogEntry.OldDataEntry
	22, // 1: riptik.audit.v1.AuditLogEntry.new_data:type_name -> riptik.audit.v1.AuditLogEntry.NewDataEntry
	2,  // 2: riptik.audit.v1.AuditContext.user:type_name -> riptik.audit.v1.ContextUser
	3,  // 3: riptik.audit.v1.AuditContext.event:type_name -> riptik.audit.v1.ContextEvent
	4,  // 4: riptik.audit.v1.AuditContext.organization:type_name -> riptik.audit.v1.ContextOrganization
	5,  // 5: riptik.audit.v1.AuditContext.device:type_name -> riptik.audit.v1.ContextDevice
	6,  // 6: riptik.audit.v1.AuditContext.api_token:type_name -> riptik.audit.v1.ContextAPIToken
	23, // 7: riptik.audit.v1.CreateAuditLogRequest.data:type_name -> riptik.audit.v1.CreateAuditLogRequest.DataEntry
	1,  // 8: riptik.audit.v1.CreateAuditLogRequest.context:type_name -> riptik.audit.v1.AuditContext
	0,  // 9: riptik.audit.v1.CreateAuditLogResponse.entry:type_name -> riptik.audit.v1.AuditLogEntry
	0,  // 10: riptik.audit.v1.QueryAuditLogsResponse.entries:type_name -> riptik.audit.v1.AuditLogEntry
	13, // 11: riptik.audit.v1.QueryAuditLogsResponse.pagination:type_name -> riptik.audit.v1.PaginationInfo
	0,  // 12: riptik.audit.v1.GetAuditLogResponse.entry:type_name -> riptik.audit.v1.AuditLogEntry
	14, // 13: riptik.audit.v1.AuditLogSummaryResponse.summary:type_name -> riptik.audit.v1.AuditSummaryEntry
	0,  // 14: riptik.audit.v1.AuditTrailResponse.trail:type_name -> riptik.audit.v1.AuditLogEntry
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_v1_audit_audit_proto_init() }
func file_v1_audit_audit_proto_init() {
	if File_v1_audit_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_audit_audit_proto_rawDesc), len(file_v1_audit_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_audit_audit_proto_goTypes,
		DependencyIndexes: file_v1_audit_audit_proto_depIdxs,
		MessageInfos:      file_v1_audit_audit_proto_msgTypes,
	}.Build()
	File_v1_audit_audit_proto = out.File
	file_v1_audit_audit_proto_goTypes = nil
	file_v1_audit_audit_proto_depIdxs = nil
}
