// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: v1/cms/article.proto

package cms

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Article struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID
	OrganizerId     int64                  `protobuf:"varint,2,opt,name=organizer_id,json=organizerId,proto3" json:"organizer_id,omitempty"`
	Slug            string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Title           map[string]string      `protobuf:"bytes,4,rep,name=title,proto3" json:"title,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`     // {"en": "Title", "vi": "Tiêu đề"}
	Content         map[string]string      `protobuf:"bytes,5,rep,name=content,proto3" json:"content,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Multi-language content
	Excerpt         map[string]string      `protobuf:"bytes,6,rep,name=excerpt,proto3" json:"excerpt,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Multi-language excerpt
	FeaturedImageId *string                `protobuf:"bytes,7,opt,name=featured_image_id,json=featuredImageId,proto3,oneof" json:"featured_image_id,omitempty"`                            // UUID of featured image
	AuthorId        *string                `protobuf:"bytes,8,opt,name=author_id,json=authorId,proto3,oneof" json:"author_id,omitempty"`                                                   // UUID
	EventId         *int64                 `protobuf:"varint,9,opt,name=event_id,json=eventId,proto3,oneof" json:"event_id,omitempty"`                                                     // Optional event reference
	Type            string                 `protobuf:"bytes,10,opt,name=type,proto3" json:"type,omitempty"`                                                                                // article type (e.g., "news", "blog")
	IsFeatured      bool                   `protobuf:"varint,11,opt,name=is_featured,json=isFeatured,proto3" json:"is_featured,omitempty"`
	Position        *int32                 `protobuf:"varint,12,opt,name=position,proto3,oneof" json:"position,omitempty"`                                                                    // Display position
	Status          string                 `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`                                                                               // "draft", "published", "archived"
	PublishDate     *string                `protobuf:"bytes,14,opt,name=publish_date,json=publishDate,proto3,oneof" json:"publish_date,omitempty"`                                            // RFC3339 timestamp
	Metadata        map[string]string      `protobuf:"bytes,15,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional metadata as JSON
	CreatedAt       string                 `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                                                        // RFC3339 timestamp
	UpdatedAt       string                 `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                                                        // RFC3339 timestamp
	FeaturedImage   *Image                 `protobuf:"bytes,18,opt,name=featured_image,json=featuredImage,proto3,oneof" json:"featured_image,omitempty"`                                      // Expanded featured image object
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_v1_cms_article_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cms_article_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_v1_cms_article_proto_rawDescGZIP(), []int{0}
}

func (x *Article) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Article) GetOrganizerId() int64 {
	if x != nil {
		return x.OrganizerId
	}
	return 0
}

func (x *Article) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Article) GetTitle() map[string]string {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *Article) GetContent() map[string]string {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Article) GetExcerpt() map[string]string {
	if x != nil {
		return x.Excerpt
	}
	return nil
}

func (x *Article) GetFeaturedImageId() string {
	if x != nil && x.FeaturedImageId != nil {
		return *x.FeaturedImageId
	}
	return ""
}

func (x *Article) GetAuthorId() string {
	if x != nil && x.AuthorId != nil {
		return *x.AuthorId
	}
	return ""
}

func (x *Article) GetEventId() int64 {
	if x != nil && x.EventId != nil {
		return *x.EventId
	}
	return 0
}

func (x *Article) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Article) GetIsFeatured() bool {
	if x != nil {
		return x.IsFeatured
	}
	return false
}

func (x *Article) GetPosition() int32 {
	if x != nil && x.Position != nil {
		return *x.Position
	}
	return 0
}

func (x *Article) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Article) GetPublishDate() string {
	if x != nil && x.PublishDate != nil {
		return *x.PublishDate
	}
	return ""
}

func (x *Article) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Article) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Article) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Article) GetFeaturedImage() *Image {
	if x != nil {
		return x.FeaturedImage
	}
	return nil
}

type ListArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrganizerId   int64                  `protobuf:"varint,1,opt,name=organizer_id,json=organizerId,proto3" json:"organizer_id,omitempty"`
	Status        *string                `protobuf:"bytes,2,opt,name=status,proto3,oneof" json:"status,omitempty"`
	EventId       *int64                 `protobuf:"varint,3,opt,name=event_id,json=eventId,proto3,oneof" json:"event_id,omitempty"`
	Type          *string                `protobuf:"bytes,4,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticlesRequest) Reset() {
	*x = ListArticlesRequest{}
	mi := &file_v1_cms_article_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesRequest) ProtoMessage() {}

func (x *ListArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cms_article_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesRequest.ProtoReflect.Descriptor instead.
func (*ListArticlesRequest) Descriptor() ([]byte, []int) {
	return file_v1_cms_article_proto_rawDescGZIP(), []int{1}
}

func (x *ListArticlesRequest) GetOrganizerId() int64 {
	if x != nil {
		return x.OrganizerId
	}
	return 0
}

func (x *ListArticlesRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *ListArticlesRequest) GetEventId() int64 {
	if x != nil && x.EventId != nil {
		return *x.EventId
	}
	return 0
}

func (x *ListArticlesRequest) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *ListArticlesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListArticlesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListArticlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Articles      []*Article             `protobuf:"bytes,2,rep,name=articles,proto3" json:"articles,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,5,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticlesResponse) Reset() {
	*x = ListArticlesResponse{}
	mi := &file_v1_cms_article_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesResponse) ProtoMessage() {}

func (x *ListArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cms_article_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesResponse.ProtoReflect.Descriptor instead.
func (*ListArticlesResponse) Descriptor() ([]byte, []int) {
	return file_v1_cms_article_proto_rawDescGZIP(), []int{2}
}

func (x *ListArticlesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListArticlesResponse) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

func (x *ListArticlesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListArticlesResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListArticlesResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ListArticlesResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                             // Article UUID or slug
	OrganizerId   *int64                 `protobuf:"varint,2,opt,name=organizer_id,json=organizerId,proto3,oneof" json:"organizer_id,omitempty"` // Required when id is a slug
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleRequest) Reset() {
	*x = GetArticleRequest{}
	mi := &file_v1_cms_article_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleRequest) ProtoMessage() {}

func (x *GetArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cms_article_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleRequest.ProtoReflect.Descriptor instead.
func (*GetArticleRequest) Descriptor() ([]byte, []int) {
	return file_v1_cms_article_proto_rawDescGZIP(), []int{3}
}

func (x *GetArticleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetArticleRequest) GetOrganizerId() int64 {
	if x != nil && x.OrganizerId != nil {
		return *x.OrganizerId
	}
	return 0
}

type GetArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Article       *Article               `protobuf:"bytes,2,opt,name=article,proto3" json:"article,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleResponse) Reset() {
	*x = GetArticleResponse{}
	mi := &file_v1_cms_article_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleResponse) ProtoMessage() {}

func (x *GetArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cms_article_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleResponse.ProtoReflect.Descriptor instead.
func (*GetArticleResponse) Descriptor() ([]byte, []int) {
	return file_v1_cms_article_proto_rawDescGZIP(), []int{4}
}

func (x *GetArticleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetArticleResponse) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

func (x *GetArticleResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *GetArticleResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetArticleByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrganizerId   int64                  `protobuf:"varint,1,opt,name=organizer_id,json=organizerId,proto3" json:"organizer_id,omitempty"`
	ArticleId     int64                  `protobuf:"varint,2,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleByIDRequest) Reset() {
	*x = GetArticleByIDRequest{}
	mi := &file_v1_cms_article_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleByIDRequest) ProtoMessage() {}

func (x *GetArticleByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cms_article_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleByIDRequest.ProtoReflect.Descriptor instead.
func (*GetArticleByIDRequest) Descriptor() ([]byte, []int) {
	return file_v1_cms_article_proto_rawDescGZIP(), []int{5}
}

func (x *GetArticleByIDRequest) GetOrganizerId() int64 {
	if x != nil {
		return x.OrganizerId
	}
	return 0
}

func (x *GetArticleByIDRequest) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

type GetArticleByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Article       *Article               `protobuf:"bytes,2,opt,name=article,proto3" json:"article,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleByIDResponse) Reset() {
	*x = GetArticleByIDResponse{}
	mi := &file_v1_cms_article_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleByIDResponse) ProtoMessage() {}

func (x *GetArticleByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cms_article_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleByIDResponse.ProtoReflect.Descriptor instead.
func (*GetArticleByIDResponse) Descriptor() ([]byte, []int) {
	return file_v1_cms_article_proto_rawDescGZIP(), []int{6}
}

func (x *GetArticleByIDResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetArticleByIDResponse) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

func (x *GetArticleByIDResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *GetArticleByIDResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type CreateArticleRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrganizerId     int64                  `protobuf:"varint,1,opt,name=organizer_id,json=organizerId,proto3" json:"organizer_id,omitempty"`
	Slug            string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Title           map[string]string      `protobuf:"bytes,3,rep,name=title,proto3" json:"title,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Content         map[string]string      `protobuf:"bytes,4,rep,name=content,proto3" json:"content,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Excerpt         map[string]string      `protobuf:"bytes,5,rep,name=excerpt,proto3" json:"excerpt,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FeaturedImageId *string                `protobuf:"bytes,6,opt,name=featured_image_id,json=featuredImageId,proto3,oneof" json:"featured_image_id,omitempty"`
	EventId         *int64                 `protobuf:"varint,7,opt,name=event_id,json=eventId,proto3,oneof" json:"event_id,omitempty"`
	Type            string                 `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	IsFeatured      bool                   `protobuf:"varint,9,opt,name=is_featured,json=isFeatured,proto3" json:"is_featured,omitempty"`
	Status          string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	PublishDate     *string                `protobuf:"bytes,11,opt,name=publish_date,json=publishDate,proto3,oneof" json:"publish_date,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateArticleRequest) Reset() {
	*x = CreateArticleRequest{}
	mi := &file_v1_cms_article_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleRequest) ProtoMessage() {}

func (x *CreateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cms_article_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleRequest.ProtoReflect.Descriptor instead.
func (*CreateArticleRequest) Descriptor() ([]byte, []int) {
	return file_v1_cms_article_proto_rawDescGZIP(), []int{7}
}

func (x *CreateArticleRequest) GetOrganizerId() int64 {
	if x != nil {
		return x.OrganizerId
	}
	return 0
}

func (x *CreateArticleRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateArticleRequest) GetTitle() map[string]string {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *CreateArticleRequest) GetContent() map[string]string {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *CreateArticleRequest) GetExcerpt() map[string]string {
	if x != nil {
		return x.Excerpt
	}
	return nil
}

func (x *CreateArticleRequest) GetFeaturedImageId() string {
	if x != nil && x.FeaturedImageId != nil {
		return *x.FeaturedImageId
	}
	return ""
}

func (x *CreateArticleRequest) GetEventId() int64 {
	if x != nil && x.EventId != nil {
		return *x.EventId
	}
	return 0
}

func (x *CreateArticleRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateArticleRequest) GetIsFeatured() bool {
	if x != nil {
		return x.IsFeatured
	}
	return false
}

func (x *CreateArticleRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateArticleRequest) GetPublishDate() string {
	if x != nil && x.PublishDate != nil {
		return *x.PublishDate
	}
	return ""
}

func (x *CreateArticleRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Article       *Article               `protobuf:"bytes,2,opt,name=article,proto3" json:"article,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleResponse) Reset() {
	*x = CreateArticleResponse{}
	mi := &file_v1_cms_article_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleResponse) ProtoMessage() {}

func (x *CreateArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cms_article_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleResponse.ProtoReflect.Descriptor instead.
func (*CreateArticleResponse) Descriptor() ([]byte, []int) {
	return file_v1_cms_article_proto_rawDescGZIP(), []int{8}
}

func (x *CreateArticleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateArticleResponse) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

func (x *CreateArticleResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *CreateArticleResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type UpdateArticleRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Article UUID
	Title           map[string]string      `protobuf:"bytes,2,rep,name=title,proto3" json:"title,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Content         map[string]string      `protobuf:"bytes,3,rep,name=content,proto3" json:"content,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Excerpt         map[string]string      `protobuf:"bytes,4,rep,name=excerpt,proto3" json:"excerpt,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FeaturedImageId *string                `protobuf:"bytes,5,opt,name=featured_image_id,json=featuredImageId,proto3,oneof" json:"featured_image_id,omitempty"`
	EventId         *int64                 `protobuf:"varint,6,opt,name=event_id,json=eventId,proto3,oneof" json:"event_id,omitempty"`
	Type            string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	IsFeatured      bool                   `protobuf:"varint,8,opt,name=is_featured,json=isFeatured,proto3" json:"is_featured,omitempty"`
	Position        *int32                 `protobuf:"varint,9,opt,name=position,proto3,oneof" json:"position,omitempty"`
	Status          string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	PublishDate     *string                `protobuf:"bytes,11,opt,name=publish_date,json=publishDate,proto3,oneof" json:"publish_date,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateArticleRequest) Reset() {
	*x = UpdateArticleRequest{}
	mi := &file_v1_cms_article_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleRequest) ProtoMessage() {}

func (x *UpdateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cms_article_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleRequest.ProtoReflect.Descriptor instead.
func (*UpdateArticleRequest) Descriptor() ([]byte, []int) {
	return file_v1_cms_article_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateArticleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateArticleRequest) GetTitle() map[string]string {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *UpdateArticleRequest) GetContent() map[string]string {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UpdateArticleRequest) GetExcerpt() map[string]string {
	if x != nil {
		return x.Excerpt
	}
	return nil
}

func (x *UpdateArticleRequest) GetFeaturedImageId() string {
	if x != nil && x.FeaturedImageId != nil {
		return *x.FeaturedImageId
	}
	return ""
}

func (x *UpdateArticleRequest) GetEventId() int64 {
	if x != nil && x.EventId != nil {
		return *x.EventId
	}
	return 0
}

func (x *UpdateArticleRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateArticleRequest) GetIsFeatured() bool {
	if x != nil {
		return x.IsFeatured
	}
	return false
}

func (x *UpdateArticleRequest) GetPosition() int32 {
	if x != nil && x.Position != nil {
		return *x.Position
	}
	return 0
}

func (x *UpdateArticleRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateArticleRequest) GetPublishDate() string {
	if x != nil && x.PublishDate != nil {
		return *x.PublishDate
	}
	return ""
}

func (x *UpdateArticleRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type UpdateArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Article       *Article               `protobuf:"bytes,2,opt,name=article,proto3" json:"article,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleResponse) Reset() {
	*x = UpdateArticleResponse{}
	mi := &file_v1_cms_article_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleResponse) ProtoMessage() {}

func (x *UpdateArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cms_article_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleResponse.ProtoReflect.Descriptor instead.
func (*UpdateArticleResponse) Descriptor() ([]byte, []int) {
	return file_v1_cms_article_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateArticleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateArticleResponse) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

func (x *UpdateArticleResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *UpdateArticleResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type DeleteArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Article UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleRequest) Reset() {
	*x = DeleteArticleRequest{}
	mi := &file_v1_cms_article_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleRequest) ProtoMessage() {}

func (x *DeleteArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cms_article_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleRequest.ProtoReflect.Descriptor instead.
func (*DeleteArticleRequest) Descriptor() ([]byte, []int) {
	return file_v1_cms_article_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteArticleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleResponse) Reset() {
	*x = DeleteArticleResponse{}
	mi := &file_v1_cms_article_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleResponse) ProtoMessage() {}

func (x *DeleteArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cms_article_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleResponse.ProtoReflect.Descriptor instead.
func (*DeleteArticleResponse) Descriptor() ([]byte, []int) {
	return file_v1_cms_article_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteArticleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteArticleResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *DeleteArticleResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type PublishArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                            // Article UUID
	PublishDate   *string                `protobuf:"bytes,2,opt,name=publish_date,json=publishDate,proto3,oneof" json:"publish_date,omitempty"` // RFC3339 timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishArticleRequest) Reset() {
	*x = PublishArticleRequest{}
	mi := &file_v1_cms_article_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishArticleRequest) ProtoMessage() {}

func (x *PublishArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cms_article_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishArticleRequest.ProtoReflect.Descriptor instead.
func (*PublishArticleRequest) Descriptor() ([]byte, []int) {
	return file_v1_cms_article_proto_rawDescGZIP(), []int{13}
}

func (x *PublishArticleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublishArticleRequest) GetPublishDate() string {
	if x != nil && x.PublishDate != nil {
		return *x.PublishDate
	}
	return ""
}

type PublishArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Article       *Article               `protobuf:"bytes,2,opt,name=article,proto3" json:"article,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishArticleResponse) Reset() {
	*x = PublishArticleResponse{}
	mi := &file_v1_cms_article_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishArticleResponse) ProtoMessage() {}

func (x *PublishArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cms_article_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishArticleResponse.ProtoReflect.Descriptor instead.
func (*PublishArticleResponse) Descriptor() ([]byte, []int) {
	return file_v1_cms_article_proto_rawDescGZIP(), []int{14}
}

func (x *PublishArticleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PublishArticleResponse) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

func (x *PublishArticleResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *PublishArticleResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type UnpublishArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Article UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnpublishArticleRequest) Reset() {
	*x = UnpublishArticleRequest{}
	mi := &file_v1_cms_article_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnpublishArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnpublishArticleRequest) ProtoMessage() {}

func (x *UnpublishArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cms_article_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnpublishArticleRequest.ProtoReflect.Descriptor instead.
func (*UnpublishArticleRequest) Descriptor() ([]byte, []int) {
	return file_v1_cms_article_proto_rawDescGZIP(), []int{15}
}

func (x *UnpublishArticleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UnpublishArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Article       *Article               `protobuf:"bytes,2,opt,name=article,proto3" json:"article,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnpublishArticleResponse) Reset() {
	*x = UnpublishArticleResponse{}
	mi := &file_v1_cms_article_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnpublishArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnpublishArticleResponse) ProtoMessage() {}

func (x *UnpublishArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cms_article_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnpublishArticleResponse.ProtoReflect.Descriptor instead.
func (*UnpublishArticleResponse) Descriptor() ([]byte, []int) {
	return file_v1_cms_article_proto_rawDescGZIP(), []int{16}
}

func (x *UnpublishArticleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnpublishArticleResponse) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

func (x *UnpublishArticleResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *UnpublishArticleResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ListFeaturedArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrganizerId   int64                  `protobuf:"varint,1,opt,name=organizer_id,json=organizerId,proto3" json:"organizer_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeaturedArticlesRequest) Reset() {
	*x = ListFeaturedArticlesRequest{}
	mi := &file_v1_cms_article_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeaturedArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeaturedArticlesRequest) ProtoMessage() {}

func (x *ListFeaturedArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cms_article_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeaturedArticlesRequest.ProtoReflect.Descriptor instead.
func (*ListFeaturedArticlesRequest) Descriptor() ([]byte, []int) {
	return file_v1_cms_article_proto_rawDescGZIP(), []int{17}
}

func (x *ListFeaturedArticlesRequest) GetOrganizerId() int64 {
	if x != nil {
		return x.OrganizerId
	}
	return 0
}

func (x *ListFeaturedArticlesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListFeaturedArticlesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListFeaturedArticlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Articles      []*Article             `protobuf:"bytes,2,rep,name=articles,proto3" json:"articles,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,5,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeaturedArticlesResponse) Reset() {
	*x = ListFeaturedArticlesResponse{}
	mi := &file_v1_cms_article_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeaturedArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeaturedArticlesResponse) ProtoMessage() {}

func (x *ListFeaturedArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cms_article_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeaturedArticlesResponse.ProtoReflect.Descriptor instead.
func (*ListFeaturedArticlesResponse) Descriptor() ([]byte, []int) {
	return file_v1_cms_article_proto_rawDescGZIP(), []int{18}
}

func (x *ListFeaturedArticlesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListFeaturedArticlesResponse) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

func (x *ListFeaturedArticlesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListFeaturedArticlesResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListFeaturedArticlesResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ListFeaturedArticlesResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ListArticlesByTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrganizerId   int64                  `protobuf:"varint,1,opt,name=organizer_id,json=organizerId,proto3" json:"organizer_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticlesByTypeRequest) Reset() {
	*x = ListArticlesByTypeRequest{}
	mi := &file_v1_cms_article_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesByTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesByTypeRequest) ProtoMessage() {}

func (x *ListArticlesByTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cms_article_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesByTypeRequest.ProtoReflect.Descriptor instead.
func (*ListArticlesByTypeRequest) Descriptor() ([]byte, []int) {
	return file_v1_cms_article_proto_rawDescGZIP(), []int{19}
}

func (x *ListArticlesByTypeRequest) GetOrganizerId() int64 {
	if x != nil {
		return x.OrganizerId
	}
	return 0
}

func (x *ListArticlesByTypeRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListArticlesByTypeRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListArticlesByTypeRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListArticlesByTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Articles      []*Article             `protobuf:"bytes,2,rep,name=articles,proto3" json:"articles,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,5,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticlesByTypeResponse) Reset() {
	*x = ListArticlesByTypeResponse{}
	mi := &file_v1_cms_article_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesByTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesByTypeResponse) ProtoMessage() {}

func (x *ListArticlesByTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cms_article_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesByTypeResponse.ProtoReflect.Descriptor instead.
func (*ListArticlesByTypeResponse) Descriptor() ([]byte, []int) {
	return file_v1_cms_article_proto_rawDescGZIP(), []int{20}
}

func (x *ListArticlesByTypeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListArticlesByTypeResponse) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

func (x *ListArticlesByTypeResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListArticlesByTypeResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListArticlesByTypeResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ListArticlesByTypeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ListRelatedArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRelatedArticlesRequest) Reset() {
	*x = ListRelatedArticlesRequest{}
	mi := &file_v1_cms_article_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRelatedArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRelatedArticlesRequest) ProtoMessage() {}

func (x *ListRelatedArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cms_article_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRelatedArticlesRequest.ProtoReflect.Descriptor instead.
func (*ListRelatedArticlesRequest) Descriptor() ([]byte, []int) {
	return file_v1_cms_article_proto_rawDescGZIP(), []int{21}
}

func (x *ListRelatedArticlesRequest) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *ListRelatedArticlesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRelatedArticlesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListRelatedArticlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Articles      []*Article             `protobuf:"bytes,2,rep,name=articles,proto3" json:"articles,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,5,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRelatedArticlesResponse) Reset() {
	*x = ListRelatedArticlesResponse{}
	mi := &file_v1_cms_article_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRelatedArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRelatedArticlesResponse) ProtoMessage() {}

func (x *ListRelatedArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cms_article_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRelatedArticlesResponse.ProtoReflect.Descriptor instead.
func (*ListRelatedArticlesResponse) Descriptor() ([]byte, []int) {
	return file_v1_cms_article_proto_rawDescGZIP(), []int{22}
}

func (x *ListRelatedArticlesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListRelatedArticlesResponse) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

func (x *ListRelatedArticlesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListRelatedArticlesResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListRelatedArticlesResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ListRelatedArticlesResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_v1_cms_article_proto protoreflect.FileDescriptor

const file_v1_cms_article_proto_rawDesc = "" +
	"\n" +
	"\x14v1/cms/article.proto\x12\rriptik.cms.v1\x1a\x12v1/cms/image.proto\"\xa3\b\n" +
	"\aArticle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\forganizer_id\x18\x02 \x01(\x03R\vorganizerId\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x127\n" +
	"\x05title\x18\x04 \x03(\v2!.riptik.cms.v1.Article.TitleEntryR\x05title\x12=\n" +
	"\acontent\x18\x05 \x03(\v2#.riptik.cms.v1.Article.ContentEntryR\acontent\x12=\n" +
	"\aexcerpt\x18\x06 \x03(\v2#.riptik.cms.v1.Article.ExcerptEntryR\aexcerpt\x12/\n" +
	"\x11featured_image_id\x18\a \x01(\tH\x00R\x0ffeaturedImageId\x88\x01\x01\x12 \n" +
	"\tauthor_id\x18\b \x01(\tH\x01R\bauthorId\x88\x01\x01\x12\x1e\n" +
	"\bevent_id\x18\t \x01(\x03H\x02R\aeventId\x88\x01\x01\x12\x12\n" +
	"\x04type\x18\n" +
	" \x01(\tR\x04type\x12\x1f\n" +
	"\vis_featured\x18\v \x01(\bR\n" +
	"isFeatured\x12\x1f\n" +
	"\bposition\x18\f \x01(\x05H\x03R\bposition\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\r \x01(\tR\x06status\x12&\n" +
	"\fpublish_date\x18\x0e \x01(\tH\x04R\vpublishDate\x88\x01\x01\x12@\n" +
	"\bmetadata\x18\x0f \x03(\v2$.riptik.cms.v1.Article.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"created_at\x18\x10 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\tR\tupdatedAt\x12@\n" +
	"\x0efeatured_image\x18\x12 \x01(\v2\x14.riptik.cms.v1.ImageH\x05R\rfeaturedImage\x88\x01\x01\x1a8\n" +
	"\n" +
	"TitleEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fContentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fExcerptEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x14\n" +
	"\x12_featured_image_idB\f\n" +
	"\n" +
	"_author_idB\v\n" +
	"\t_event_idB\v\n" +
	"\t_positionB\x0f\n" +
	"\r_publish_dateB\x11\n" +
	"\x0f_featured_image\"\xdd\x01\n" +
	"\x13ListArticlesRequest\x12!\n" +
	"\forganizer_id\x18\x01 \x01(\x03R\vorganizerId\x12\x1b\n" +
	"\x06status\x18\x02 \x01(\tH\x00R\x06status\x88\x01\x01\x12\x1e\n" +
	"\bevent_id\x18\x03 \x01(\x03H\x01R\aeventId\x88\x01\x01\x12\x17\n" +
	"\x04type\x18\x04 \x01(\tH\x02R\x04type\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offsetB\t\n" +
	"\a_statusB\v\n" +
	"\t_event_idB\a\n" +
	"\x05_type\"\xd4\x01\n" +
	"\x14ListArticlesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x122\n" +
	"\barticles\x18\x02 \x03(\v2\x16.riptik.cms.v1.ArticleR\barticles\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x12\x1d\n" +
	"\n" +
	"error_code\x18\x05 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"\\\n" +
	"\x11GetArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\forganizer_id\x18\x02 \x01(\x03H\x00R\vorganizerId\x88\x01\x01B\x0f\n" +
	"\r_organizer_id\"\xa4\x01\n" +
	"\x12GetArticleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x120\n" +
	"\aarticle\x18\x02 \x01(\v2\x16.riptik.cms.v1.ArticleR\aarticle\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"Y\n" +
	"\x15GetArticleByIDRequest\x12!\n" +
	"\forganizer_id\x18\x01 \x01(\x03R\vorganizerId\x12\x1d\n" +
	"\n" +
	"article_id\x18\x02 \x01(\x03R\tarticleId\"\xa8\x01\n" +
	"\x16GetArticleByIDResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x120\n" +
	"\aarticle\x18\x02 \x01(\v2\x16.riptik.cms.v1.ArticleR\aarticle\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\xe3\x06\n" +
	"\x14CreateArticleRequest\x12!\n" +
	"\forganizer_id\x18\x01 \x01(\x03R\vorganizerId\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12D\n" +
	"\x05title\x18\x03 \x03(\v2..riptik.cms.v1.CreateArticleRequest.TitleEntryR\x05title\x12J\n" +
	"\acontent\x18\x04 \x03(\v20.riptik.cms.v1.CreateArticleRequest.ContentEntryR\acontent\x12J\n" +
	"\aexcerpt\x18\x05 \x03(\v20.riptik.cms.v1.CreateArticleRequest.ExcerptEntryR\aexcerpt\x12/\n" +
	"\x11featured_image_id\x18\x06 \x01(\tH\x00R\x0ffeaturedImageId\x88\x01\x01\x12\x1e\n" +
	"\bevent_id\x18\a \x01(\x03H\x01R\aeventId\x88\x01\x01\x12\x12\n" +
	"\x04type\x18\b \x01(\tR\x04type\x12\x1f\n" +
	"\vis_featured\x18\t \x01(\bR\n" +
	"isFeatured\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12&\n" +
	"\fpublish_date\x18\v \x01(\tH\x02R\vpublishDate\x88\x01\x01\x12M\n" +
	"\bmetadata\x18\f \x03(\v21.riptik.cms.v1.CreateArticleRequest.MetadataEntryR\bmetadata\x1a8\n" +
	"\n" +
	"TitleEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fContentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fExcerptEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x14\n" +
	"\x12_featured_image_idB\v\n" +
	"\t_event_idB\x0f\n" +
	"\r_publish_date\"\xa7\x01\n" +
	"\x15CreateArticleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x120\n" +
	"\aarticle\x18\x02 \x01(\v2\x16.riptik.cms.v1.ArticleR\aarticle\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\xea\x06\n" +
	"\x14UpdateArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12D\n" +
	"\x05title\x18\x02 \x03(\v2..riptik.cms.v1.UpdateArticleRequest.TitleEntryR\x05title\x12J\n" +
	"\acontent\x18\x03 \x03(\v20.riptik.cms.v1.UpdateArticleRequest.ContentEntryR\acontent\x12J\n" +
	"\aexcerpt\x18\x04 \x03(\v20.riptik.cms.v1.UpdateArticleRequest.ExcerptEntryR\aexcerpt\x12/\n" +
	"\x11featured_image_id\x18\x05 \x01(\tH\x00R\x0ffeaturedImageId\x88\x01\x01\x12\x1e\n" +
	"\bevent_id\x18\x06 \x01(\x03H\x01R\aeventId\x88\x01\x01\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12\x1f\n" +
	"\vis_featured\x18\b \x01(\bR\n" +
	"isFeatured\x12\x1f\n" +
	"\bposition\x18\t \x01(\x05H\x02R\bposition\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12&\n" +
	"\fpublish_date\x18\v \x01(\tH\x03R\vpublishDate\x88\x01\x01\x12M\n" +
	"\bmetadata\x18\f \x03(\v21.riptik.cms.v1.UpdateArticleRequest.MetadataEntryR\bmetadata\x1a8\n" +
	"\n" +
	"TitleEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fContentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fExcerptEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x14\n" +
	"\x12_featured_image_idB\v\n" +
	"\t_event_idB\v\n" +
	"\t_positionB\x0f\n" +
	"\r_publish_date\"\xa7\x01\n" +
	"\x15UpdateArticleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x120\n" +
	"\aarticle\x18\x02 \x01(\v2\x16.riptik.cms.v1.ArticleR\aarticle\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"&\n" +
	"\x14DeleteArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"u\n" +
	"\x15DeleteArticleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"`\n" +
	"\x15PublishArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\fpublish_date\x18\x02 \x01(\tH\x00R\vpublishDate\x88\x01\x01B\x0f\n" +
	"\r_publish_date\"\xa8\x01\n" +
	"\x16PublishArticleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x120\n" +
	"\aarticle\x18\x02 \x01(\v2\x16.riptik.cms.v1.ArticleR\aarticle\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\")\n" +
	"\x17UnpublishArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xaa\x01\n" +
	"\x18UnpublishArticleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x120\n" +
	"\aarticle\x18\x02 \x01(\v2\x16.riptik.cms.v1.ArticleR\aarticle\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"n\n" +
	"\x1bListFeaturedArticlesRequest\x12!\n" +
	"\forganizer_id\x18\x01 \x01(\x03R\vorganizerId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\xdc\x01\n" +
	"\x1cListFeaturedArticlesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x122\n" +
	"\barticles\x18\x02 \x03(\v2\x16.riptik.cms.v1.ArticleR\barticles\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x12\x1d\n" +
	"\n" +
	"error_code\x18\x05 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"\x80\x01\n" +
	"\x19ListArticlesByTypeRequest\x12!\n" +
	"\forganizer_id\x18\x01 \x01(\x03R\vorganizerId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\xda\x01\n" +
	"\x1aListArticlesByTypeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x122\n" +
	"\barticles\x18\x02 \x03(\v2\x16.riptik.cms.v1.ArticleR\barticles\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x12\x1d\n" +
	"\n" +
	"error_code\x18\x05 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"i\n" +
	"\x1aListRelatedArticlesRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\xdb\x01\n" +
	"\x1bListRelatedArticlesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x122\n" +
	"\barticles\x18\x02 \x03(\v2\x16.riptik.cms.v1.ArticleR\barticles\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x12\x1d\n" +
	"\n" +
	"error_code\x18\x05 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessageB&Z$github.com/riptik/services/pb/v1/cmsb\x06proto3"

var (
	file_v1_cms_article_proto_rawDescOnce sync.Once
	file_v1_cms_article_proto_rawDescData []byte
)

func file_v1_cms_article_proto_rawDescGZIP() []byte {
	file_v1_cms_article_proto_rawDescOnce.Do(func() {
		file_v1_cms_article_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_cms_article_proto_rawDesc), len(file_v1_cms_article_proto_rawDesc)))
	})
	return file_v1_cms_article_proto_rawDescData
}

var file_v1_cms_article_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_v1_cms_article_proto_goTypes = []any{
	(*Article)(nil),                      // 0: riptik.cms.v1.Article
	(*ListArticlesRequest)(nil),          // 1: riptik.cms.v1.ListArticlesRequest
	(*ListArticlesResponse)(nil),         // 2: riptik.cms.v1.ListArticlesResponse
	(*GetArticleRequest)(nil),            // 3: riptik.cms.v1.GetArticleRequest
	(*GetArticleResponse)(nil),           // 4: riptik.cms.v1.GetArticleResponse
	(*GetArticleByIDRequest)(nil),        // 5: riptik.cms.v1.GetArticleByIDRequest
	(*GetArticleByIDResponse)(nil),       // 6: riptik.cms.v1.GetArticleByIDResponse
	(*CreateArticleRequest)(nil),         // 7: riptik.cms.v1.CreateArticleRequest
	(*CreateArticleResponse)(nil),        // 8: riptik.cms.v1.CreateArticleResponse
	(*UpdateArticleRequest)(nil),         // 9: riptik.cms.v1.UpdateArticleRequest
	(*UpdateArticleResponse)(nil),        // 10: riptik.cms.v1.UpdateArticleResponse
	(*DeleteArticleRequest)(nil),         // 11: riptik.cms.v1.DeleteArticleRequest
	(*DeleteArticleResponse)(nil),        // 12: riptik.cms.v1.DeleteArticleResponse
	(*PublishArticleRequest)(nil),        // 13: riptik.cms.v1.PublishArticleRequest
	(*PublishArticleResponse)(nil),       // 14: riptik.cms.v1.PublishArticleResponse
	(*UnpublishArticleRequest)(nil),      // 15: riptik.cms.v1.UnpublishArticleRequest
	(*UnpublishArticleResponse)(nil),     // 16: riptik.cms.v1.UnpublishArticleResponse
	(*ListFeaturedArticlesRequest)(nil),  // 17: riptik.cms.v1.ListFeaturedArticlesRequest
	(*ListFeaturedArticlesResponse)(nil), // 18: riptik.cms.v1.ListFeaturedArticlesResponse
	(*ListArticlesByTypeRequest)(nil),    // 19: riptik.cms.v1.ListArticlesByTypeRequest
	(*ListArticlesByTypeResponse)(nil),   // 20: riptik.cms.v1.ListArticlesByTypeResponse
	(*ListRelatedArticlesRequest)(nil),   // 21: riptik.cms.v1.ListRelatedArticlesRequest
	(*ListRelatedArticlesResponse)(nil),  // 22: riptik.cms.v1.ListRelatedArticlesResponse
	nil,                                  // 23: riptik.cms.v1.Article.TitleEntry
	nil,                                  // 24: riptik.cms.v1.Article.ContentEntry
	nil,                                  // 25: riptik.cms.v1.Article.ExcerptEntry
	nil,                                  // 26: riptik.cms.v1.Article.MetadataEntry
	nil,                                  // 27: riptik.cms.v1.CreateArticleRequest.TitleEntry
	nil,                                  // 28: riptik.cms.v1.CreateArticleRequest.ContentEntry
	nil,                                  // 29: riptik.cms.v1.CreateArticleRequest.ExcerptEntry
	nil,                                  // 30: riptik.cms.v1.CreateArticleRequest.MetadataEntry
	nil,                                  // 31: riptik.cms.v1.UpdateArticleRequest.TitleEntry
	nil,                                  // 32: riptik.cms.v1.UpdateArticleRequest.ContentEntry
	nil,                                  // 33: riptik.cms.v1.UpdateArticleRequest.ExcerptEntry
	nil,                                  // 34: riptik.cms.v1.UpdateArticleRequest.MetadataEntry
	(*Image)(nil),                        // 35: riptik.cms.v1.Image
}
var file_v1_cms_article_proto_depIdxs = []int32{
	23, // 0: riptik.cms.v1.Article.title:type_name -> riptik.cms.v1.Article.TitleEntry
	24, // 1: riptik.cms.v1.Article.content:type_name -> riptik.cms.v1.Article.ContentEntry
	25, // 2: riptik.cms.v1.Article.excerpt:type_name -> riptik.cms.v1.Article.ExcerptEntry
	26, // 3: riptik.cms.v1.Article.metadata:type_name -> riptik.cms.v1.Article.MetadataEntry
	35, // 4: riptik.cms.v1.Article.featured_image:type_name -> riptik.cms.v1.Image
	0,  // 5: riptik.cms.v1.ListArticlesResponse.articles:type_name -> riptik.cms.v1.Article
	0,  // 6: riptik.cms.v1.GetArticleResponse.article:type_name -> riptik.cms.v1.Article
	0,  // 7: riptik.cms.v1.GetArticleByIDResponse.article:type_name -> riptik.cms.v1.Article
	27, // 8: riptik.cms.v1.CreateArticleRequest.title:type_name -> riptik.cms.v1.CreateArticleRequest.TitleEntry
	28, // 9: riptik.cms.v1.CreateArticleRequest.content:type_name -> riptik.cms.v1.CreateArticleRequest.ContentEntry
	29, // 10: riptik.cms.v1.CreateArticleRequest.excerpt:type_name -> riptik.cms.v1.CreateArticleRequest.ExcerptEntry
	30, // 11: riptik.cms.v1.CreateArticleRequest.metadata:type_name -> riptik.cms.v1.CreateArticleRequest.MetadataEntry
	0,  // 12: riptik.cms.v1.CreateArticleResponse.article:type_name -> riptik.cms.v1.Article
	31, // 13: riptik.cms.v1.UpdateArticleRequest.title:type_name -> riptik.cms.v1.UpdateArticleRequest.TitleEntry
	32, // 14: riptik.cms.v1.UpdateArticleRequest.content:type_name -> riptik.cms.v1.UpdateArticleRequest.ContentEntry
	33, // 15: riptik.cms.v1.UpdateArticleRequest.excerpt:type_name -> riptik.cms.v1.UpdateArticleRequest.ExcerptEntry
	34, // 16: riptik.cms.v1.UpdateArticleRequest.metadata:type_name -> riptik.cms.v1.UpdateArticleRequest.MetadataEntry
	0,  // 17: riptik.cms.v1.UpdateArticleResponse.article:type_name -> riptik.cms.v1.Article
	0,  // 18: riptik.cms.v1.PublishArticleResponse.article:type_name -> riptik.cms.v1.Article
	0,  // 19: riptik.cms.v1.UnpublishArticleResponse.article:type_name -> riptik.cms.v1.Article
	0,  // 20: riptik.cms.v1.ListFeaturedArticlesResponse.articles:type_name -> riptik.cms.v1.Article
	0,  // 21: riptik.cms.v1.ListArticlesByTypeResponse.articles:type_name -> riptik.cms.v1.Article
	0,  // 22: riptik.cms.v1.ListRelatedArticlesResponse.articles:type_name -> riptik.cms.v1.Article
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_v1_cms_article_proto_init() }
func file_v1_cms_article_proto_init() {
	if File_v1_cms_article_proto != nil {
		return
	}
	file_v1_cms_image_proto_init()
	file_v1_cms_article_proto_msgTypes[0].OneofWrappers = []any{}
	file_v1_cms_article_proto_msgTypes[1].OneofWrappers = []any{}
	file_v1_cms_article_proto_msgTypes[3].OneofWrappers = []any{}
	file_v1_cms_article_proto_msgTypes[7].OneofWrappers = []any{}
	file_v1_cms_article_proto_msgTypes[9].OneofWrappers = []any{}
	file_v1_cms_article_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_cms_article_proto_rawDesc), len(file_v1_cms_article_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_cms_article_proto_goTypes,
		DependencyIndexes: file_v1_cms_article_proto_depIdxs,
		MessageInfos:      file_v1_cms_article_proto_msgTypes,
	}.Build()
	File_v1_cms_article_proto = out.File
	file_v1_cms_article_proto_goTypes = nil
	file_v1_cms_article_proto_depIdxs = nil
}
