// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.12
// source: v1/booking/addon.proto

package booking

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Domain model: ItemAddon
type ItemAddon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AddonCategory int64  `protobuf:"varint,2,opt,name=addon_category,json=addonCategory,proto3" json:"addon_category,omitempty"`
	MinCount      int32  `protobuf:"varint,3,opt,name=min_count,json=minCount,proto3" json:"min_count,omitempty"`
	MaxCount      int32  `protobuf:"varint,4,opt,name=max_count,json=maxCount,proto3" json:"max_count,omitempty"`
	Position      int32  `protobuf:"varint,5,opt,name=position,proto3" json:"position,omitempty"`
	PriceIncluded bool   `protobuf:"varint,6,opt,name=price_included,json=priceIncluded,proto3" json:"price_included,omitempty"` // Is price included
	MultiAllowed  bool   `protobuf:"varint,7,opt,name=multi_allowed,json=multiAllowed,proto3" json:"multi_allowed,omitempty"`    // Multiple selections allowed
	Created       string `protobuf:"bytes,8,opt,name=created,proto3" json:"created,omitempty"`                                   // ISO datetime (created)
	LastModified  string `protobuf:"bytes,9,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`     // ISO datetime (last modified)
}

func (x *ItemAddon) Reset() {
	*x = ItemAddon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_booking_addon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemAddon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemAddon) ProtoMessage() {}

func (x *ItemAddon) ProtoReflect() protoreflect.Message {
	mi := &file_v1_booking_addon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemAddon.ProtoReflect.Descriptor instead.
func (*ItemAddon) Descriptor() ([]byte, []int) {
	return file_v1_booking_addon_proto_rawDescGZIP(), []int{0}
}

func (x *ItemAddon) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ItemAddon) GetAddonCategory() int64 {
	if x != nil {
		return x.AddonCategory
	}
	return 0
}

func (x *ItemAddon) GetMinCount() int32 {
	if x != nil {
		return x.MinCount
	}
	return 0
}

func (x *ItemAddon) GetMaxCount() int32 {
	if x != nil {
		return x.MaxCount
	}
	return 0
}

func (x *ItemAddon) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *ItemAddon) GetPriceIncluded() bool {
	if x != nil {
		return x.PriceIncluded
	}
	return false
}

func (x *ItemAddon) GetMultiAllowed() bool {
	if x != nil {
		return x.MultiAllowed
	}
	return false
}

func (x *ItemAddon) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *ItemAddon) GetLastModified() string {
	if x != nil {
		return x.LastModified
	}
	return ""
}

// Requests
type ListAddonsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Organizer string `protobuf:"bytes,1,opt,name=organizer,proto3" json:"organizer,omitempty"` // Organizer slug (required)
	Event     string `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`         // Event slug (required)
	Item      string `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`           // Item ID or slug (required)
}

func (x *ListAddonsRequest) Reset() {
	*x = ListAddonsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_booking_addon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAddonsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddonsRequest) ProtoMessage() {}

func (x *ListAddonsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_booking_addon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddonsRequest.ProtoReflect.Descriptor instead.
func (*ListAddonsRequest) Descriptor() ([]byte, []int) {
	return file_v1_booking_addon_proto_rawDescGZIP(), []int{1}
}

func (x *ListAddonsRequest) GetOrganizer() string {
	if x != nil {
		return x.Organizer
	}
	return ""
}

func (x *ListAddonsRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *ListAddonsRequest) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

type GetAddonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Organizer string `protobuf:"bytes,1,opt,name=organizer,proto3" json:"organizer,omitempty"`             // Organizer slug (required)
	Event     string `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`                     // Event slug (required)
	Item      string `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`                       // Item ID or slug (required)
	AddonId   int64  `protobuf:"varint,4,opt,name=addon_id,json=addonId,proto3" json:"addon_id,omitempty"` // Addon ID (required)
}

func (x *GetAddonRequest) Reset() {
	*x = GetAddonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_booking_addon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAddonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddonRequest) ProtoMessage() {}

func (x *GetAddonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_booking_addon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddonRequest.ProtoReflect.Descriptor instead.
func (*GetAddonRequest) Descriptor() ([]byte, []int) {
	return file_v1_booking_addon_proto_rawDescGZIP(), []int{2}
}

func (x *GetAddonRequest) GetOrganizer() string {
	if x != nil {
		return x.Organizer
	}
	return ""
}

func (x *GetAddonRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *GetAddonRequest) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

func (x *GetAddonRequest) GetAddonId() int64 {
	if x != nil {
		return x.AddonId
	}
	return 0
}

type CreateAddonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Organizer string           `protobuf:"bytes,1,opt,name=organizer,proto3" json:"organizer,omitempty"` // Organizer slug (required)
	Event     string           `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`         // Event slug (required)
	Item      string           `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`           // Item ID or slug (required)
	Data      *AddonCreateData `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`           // Addon data (required)
}

func (x *CreateAddonRequest) Reset() {
	*x = CreateAddonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_booking_addon_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAddonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddonRequest) ProtoMessage() {}

func (x *CreateAddonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_booking_addon_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddonRequest.ProtoReflect.Descriptor instead.
func (*CreateAddonRequest) Descriptor() ([]byte, []int) {
	return file_v1_booking_addon_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAddonRequest) GetOrganizer() string {
	if x != nil {
		return x.Organizer
	}
	return ""
}

func (x *CreateAddonRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *CreateAddonRequest) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

func (x *CreateAddonRequest) GetData() *AddonCreateData {
	if x != nil {
		return x.Data
	}
	return nil
}

type AddonCreateData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddonCategory int64 `protobuf:"varint,1,opt,name=addon_category,json=addonCategory,proto3" json:"addon_category,omitempty"` // Addon category ID (required)
	MinCount      int32 `protobuf:"varint,2,opt,name=min_count,json=minCount,proto3" json:"min_count,omitempty"`                // Minimum count (required)
	MaxCount      int32 `protobuf:"varint,3,opt,name=max_count,json=maxCount,proto3" json:"max_count,omitempty"`                // Maximum count (required)
	Position      int32 `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`                                // Position (required)
	PriceIncluded bool  `protobuf:"varint,5,opt,name=price_included,json=priceIncluded,proto3" json:"price_included,omitempty"` // Price included flag
	MultiAllowed  bool  `protobuf:"varint,6,opt,name=multi_allowed,json=multiAllowed,proto3" json:"multi_allowed,omitempty"`    // Multi-select allowed flag
}

func (x *AddonCreateData) Reset() {
	*x = AddonCreateData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_booking_addon_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddonCreateData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddonCreateData) ProtoMessage() {}

func (x *AddonCreateData) ProtoReflect() protoreflect.Message {
	mi := &file_v1_booking_addon_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddonCreateData.ProtoReflect.Descriptor instead.
func (*AddonCreateData) Descriptor() ([]byte, []int) {
	return file_v1_booking_addon_proto_rawDescGZIP(), []int{4}
}

func (x *AddonCreateData) GetAddonCategory() int64 {
	if x != nil {
		return x.AddonCategory
	}
	return 0
}

func (x *AddonCreateData) GetMinCount() int32 {
	if x != nil {
		return x.MinCount
	}
	return 0
}

func (x *AddonCreateData) GetMaxCount() int32 {
	if x != nil {
		return x.MaxCount
	}
	return 0
}

func (x *AddonCreateData) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *AddonCreateData) GetPriceIncluded() bool {
	if x != nil {
		return x.PriceIncluded
	}
	return false
}

func (x *AddonCreateData) GetMultiAllowed() bool {
	if x != nil {
		return x.MultiAllowed
	}
	return false
}

type UpdateAddonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Organizer string           `protobuf:"bytes,1,opt,name=organizer,proto3" json:"organizer,omitempty"`             // Organizer slug (required)
	Event     string           `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`                     // Event slug (required)
	Item      string           `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`                       // Item ID or slug (required)
	AddonId   int64            `protobuf:"varint,4,opt,name=addon_id,json=addonId,proto3" json:"addon_id,omitempty"` // Addon ID (required)
	Data      *AddonUpdateData `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`                       // Addon data to update
}

func (x *UpdateAddonRequest) Reset() {
	*x = UpdateAddonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_booking_addon_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAddonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAddonRequest) ProtoMessage() {}

func (x *UpdateAddonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_booking_addon_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAddonRequest.ProtoReflect.Descriptor instead.
func (*UpdateAddonRequest) Descriptor() ([]byte, []int) {
	return file_v1_booking_addon_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAddonRequest) GetOrganizer() string {
	if x != nil {
		return x.Organizer
	}
	return ""
}

func (x *UpdateAddonRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *UpdateAddonRequest) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

func (x *UpdateAddonRequest) GetAddonId() int64 {
	if x != nil {
		return x.AddonId
	}
	return 0
}

func (x *UpdateAddonRequest) GetData() *AddonUpdateData {
	if x != nil {
		return x.Data
	}
	return nil
}

type AddonUpdateData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MinCount      int32 `protobuf:"varint,1,opt,name=min_count,json=minCount,proto3" json:"min_count,omitempty"`                // Minimum count (optional)
	MaxCount      int32 `protobuf:"varint,2,opt,name=max_count,json=maxCount,proto3" json:"max_count,omitempty"`                // Maximum count (optional)
	Position      int32 `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`                                // Position (optional)
	PriceIncluded bool  `protobuf:"varint,4,opt,name=price_included,json=priceIncluded,proto3" json:"price_included,omitempty"` // Price included flag (optional)
	MultiAllowed  bool  `protobuf:"varint,5,opt,name=multi_allowed,json=multiAllowed,proto3" json:"multi_allowed,omitempty"`    // Multi-select allowed flag (optional)
}

func (x *AddonUpdateData) Reset() {
	*x = AddonUpdateData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_booking_addon_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddonUpdateData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddonUpdateData) ProtoMessage() {}

func (x *AddonUpdateData) ProtoReflect() protoreflect.Message {
	mi := &file_v1_booking_addon_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddonUpdateData.ProtoReflect.Descriptor instead.
func (*AddonUpdateData) Descriptor() ([]byte, []int) {
	return file_v1_booking_addon_proto_rawDescGZIP(), []int{6}
}

func (x *AddonUpdateData) GetMinCount() int32 {
	if x != nil {
		return x.MinCount
	}
	return 0
}

func (x *AddonUpdateData) GetMaxCount() int32 {
	if x != nil {
		return x.MaxCount
	}
	return 0
}

func (x *AddonUpdateData) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *AddonUpdateData) GetPriceIncluded() bool {
	if x != nil {
		return x.PriceIncluded
	}
	return false
}

func (x *AddonUpdateData) GetMultiAllowed() bool {
	if x != nil {
		return x.MultiAllowed
	}
	return false
}

type DeleteAddonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Organizer string `protobuf:"bytes,1,opt,name=organizer,proto3" json:"organizer,omitempty"`             // Organizer slug (required)
	Event     string `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`                     // Event slug (required)
	Item      string `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`                       // Item ID or slug (required)
	AddonId   int64  `protobuf:"varint,4,opt,name=addon_id,json=addonId,proto3" json:"addon_id,omitempty"` // Addon ID (required)
}

func (x *DeleteAddonRequest) Reset() {
	*x = DeleteAddonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_booking_addon_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAddonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddonRequest) ProtoMessage() {}

func (x *DeleteAddonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_booking_addon_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddonRequest.ProtoReflect.Descriptor instead.
func (*DeleteAddonRequest) Descriptor() ([]byte, []int) {
	return file_v1_booking_addon_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAddonRequest) GetOrganizer() string {
	if x != nil {
		return x.Organizer
	}
	return ""
}

func (x *DeleteAddonRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *DeleteAddonRequest) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

func (x *DeleteAddonRequest) GetAddonId() int64 {
	if x != nil {
		return x.AddonId
	}
	return 0
}

// Responses
type ListAddonsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success      bool         `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Addons       []*ItemAddon `protobuf:"bytes,2,rep,name=addons,proto3" json:"addons,omitempty"`
	ErrorCode    string       `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage string       `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *ListAddonsResponse) Reset() {
	*x = ListAddonsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_booking_addon_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAddonsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddonsResponse) ProtoMessage() {}

func (x *ListAddonsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_booking_addon_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddonsResponse.ProtoReflect.Descriptor instead.
func (*ListAddonsResponse) Descriptor() ([]byte, []int) {
	return file_v1_booking_addon_proto_rawDescGZIP(), []int{8}
}

func (x *ListAddonsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListAddonsResponse) GetAddons() []*ItemAddon {
	if x != nil {
		return x.Addons
	}
	return nil
}

func (x *ListAddonsResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ListAddonsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetAddonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success      bool       `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Addon        *ItemAddon `protobuf:"bytes,2,opt,name=addon,proto3" json:"addon,omitempty"`
	ErrorCode    string     `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage string     `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *GetAddonResponse) Reset() {
	*x = GetAddonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_booking_addon_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAddonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddonResponse) ProtoMessage() {}

func (x *GetAddonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_booking_addon_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddonResponse.ProtoReflect.Descriptor instead.
func (*GetAddonResponse) Descriptor() ([]byte, []int) {
	return file_v1_booking_addon_proto_rawDescGZIP(), []int{9}
}

func (x *GetAddonResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetAddonResponse) GetAddon() *ItemAddon {
	if x != nil {
		return x.Addon
	}
	return nil
}

func (x *GetAddonResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *GetAddonResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type CreateAddonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success      bool       `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Addon        *ItemAddon `protobuf:"bytes,2,opt,name=addon,proto3" json:"addon,omitempty"`
	ErrorCode    string     `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage string     `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *CreateAddonResponse) Reset() {
	*x = CreateAddonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_booking_addon_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAddonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddonResponse) ProtoMessage() {}

func (x *CreateAddonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_booking_addon_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddonResponse.ProtoReflect.Descriptor instead.
func (*CreateAddonResponse) Descriptor() ([]byte, []int) {
	return file_v1_booking_addon_proto_rawDescGZIP(), []int{10}
}

func (x *CreateAddonResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateAddonResponse) GetAddon() *ItemAddon {
	if x != nil {
		return x.Addon
	}
	return nil
}

func (x *CreateAddonResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *CreateAddonResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type UpdateAddonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success      bool       `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Addon        *ItemAddon `protobuf:"bytes,2,opt,name=addon,proto3" json:"addon,omitempty"`
	ErrorCode    string     `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage string     `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *UpdateAddonResponse) Reset() {
	*x = UpdateAddonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_booking_addon_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAddonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAddonResponse) ProtoMessage() {}

func (x *UpdateAddonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_booking_addon_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAddonResponse.ProtoReflect.Descriptor instead.
func (*UpdateAddonResponse) Descriptor() ([]byte, []int) {
	return file_v1_booking_addon_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateAddonResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateAddonResponse) GetAddon() *ItemAddon {
	if x != nil {
		return x.Addon
	}
	return nil
}

func (x *UpdateAddonResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *UpdateAddonResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type DeleteAddonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success      bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message      string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ErrorCode    string `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *DeleteAddonResponse) Reset() {
	*x = DeleteAddonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_booking_addon_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAddonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddonResponse) ProtoMessage() {}

func (x *DeleteAddonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_booking_addon_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddonResponse.ProtoReflect.Descriptor instead.
func (*DeleteAddonResponse) Descriptor() ([]byte, []int) {
	return file_v1_booking_addon_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteAddonResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteAddonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteAddonResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *DeleteAddonResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_v1_booking_addon_proto protoreflect.FileDescriptor

var file_v1_booking_addon_proto_rawDesc = []byte{
	0x0a, 0x16, 0x76, 0x31, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2f, 0x61, 0x64, 0x64,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6b,
	0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x22, 0xa3, 0x02, 0x0a, 0x09,
	0x49, 0x74, 0x65, 0x6d, 0x41, 0x64, 0x64, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x64, 0x64,
	0x6f, 0x6e, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0d, 0x61, 0x64, 0x64, 0x6f, 0x6e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x69, 0x6e, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x69, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x6d, 0x61, 0x78, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x6d, 0x61, 0x78, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f,
	0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x64, 0x12, 0x23, 0x0a,
	0x0d, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x5f, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x41, 0x6c, 0x6c, 0x6f, 0x77,
	0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d,
	0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65,
	0x64, 0x22, 0x5b, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x64, 0x6f, 0x6e, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69,
	0x7a, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x72, 0x67, 0x61, 0x6e,
	0x69, 0x7a, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x74,
	0x65, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x74,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x65, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x64, 0x64,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x6f, 0x6e, 0x49, 0x64, 0x22, 0x94, 0x01, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41,
	0x64, 0x64, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6f,
	0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69,
	0x74, 0x65, 0x6d, 0x12, 0x36, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6b, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x6f, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xda, 0x01, 0x0a, 0x0f,
	0x41, 0x64, 0x64, 0x6f, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x25, 0x0a, 0x0e, 0x61, 0x64, 0x64, 0x6f, 0x6e, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x61, 0x64, 0x64, 0x6f, 0x6e, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x69, 0x6e, 0x5f, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x69, 0x6e, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x78, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x61, 0x78, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x70, 0x72, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x63, 0x6c, 0x75,
	0x64, 0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x5f, 0x61, 0x6c, 0x6c,
	0x6f, 0x77, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x6d, 0x75, 0x6c, 0x74,
	0x69, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x22, 0xaf, 0x01, 0x0a, 0x12, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x41, 0x64, 0x64, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x65, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x64, 0x64, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x61, 0x64, 0x64, 0x6f, 0x6e,
	0x49, 0x64, 0x12, 0x36, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x22, 0x2e, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6b, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e,
	0x67, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x6f, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xb3, 0x01, 0x0a, 0x0f, 0x41,
	0x64, 0x64, 0x6f, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1b,
	0x0a, 0x09, 0x6d, 0x69, 0x6e, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x6d, 0x69, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d,
	0x61, 0x78, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x6d, 0x61, 0x78, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x6e,
	0x63, 0x6c, 0x75, 0x64, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x49, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x6d,
	0x75, 0x6c, 0x74, 0x69, 0x5f, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0c, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64,
	0x22, 0x77, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x64, 0x64, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69,
	0x7a, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x72, 0x67, 0x61, 0x6e,
	0x69, 0x7a, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x74,
	0x65, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x12, 0x19,
	0x0a, 0x08, 0x61, 0x64, 0x64, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0xa8, 0x01, 0x0a, 0x12, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x64, 0x64, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x34, 0x0a, 0x06, 0x61, 0x64,
	0x64, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6b, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x41, 0x64, 0x64, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x64, 0x64, 0x6f, 0x6e, 0x73,
	0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0xa4, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x32, 0x0a, 0x05, 0x61, 0x64, 0x64, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6b, 0x2e, 0x62, 0x6f, 0x6f, 0x6b,
	0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x41, 0x64, 0x64, 0x6f, 0x6e,
	0x52, 0x05, 0x61, 0x64, 0x64, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xa7, 0x01, 0x0a, 0x13,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x64, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x32, 0x0a,
	0x05, 0x61, 0x64, 0x64, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6b, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31,
	0x2e, 0x49, 0x74, 0x65, 0x6d, 0x41, 0x64, 0x64, 0x6f, 0x6e, 0x52, 0x05, 0x61, 0x64, 0x64, 0x6f,
	0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xa7, 0x01, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x41, 0x64, 0x64, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x32, 0x0a, 0x05, 0x61, 0x64, 0x64, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6b, 0x2e,
	0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x41,
	0x64, 0x64, 0x6f, 0x6e, 0x52, 0x05, 0x61, 0x64, 0x64, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x8d, 0x01, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x64, 0x64, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42,
	0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6b, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x62,
	0x2f, 0x76, 0x31, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_v1_booking_addon_proto_rawDescOnce sync.Once
	file_v1_booking_addon_proto_rawDescData = file_v1_booking_addon_proto_rawDesc
)

func file_v1_booking_addon_proto_rawDescGZIP() []byte {
	file_v1_booking_addon_proto_rawDescOnce.Do(func() {
		file_v1_booking_addon_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_booking_addon_proto_rawDescData)
	})
	return file_v1_booking_addon_proto_rawDescData
}

var file_v1_booking_addon_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_v1_booking_addon_proto_goTypes = []interface{}{
	(*ItemAddon)(nil),           // 0: riptik.booking.v1.ItemAddon
	(*ListAddonsRequest)(nil),   // 1: riptik.booking.v1.ListAddonsRequest
	(*GetAddonRequest)(nil),     // 2: riptik.booking.v1.GetAddonRequest
	(*CreateAddonRequest)(nil),  // 3: riptik.booking.v1.CreateAddonRequest
	(*AddonCreateData)(nil),     // 4: riptik.booking.v1.AddonCreateData
	(*UpdateAddonRequest)(nil),  // 5: riptik.booking.v1.UpdateAddonRequest
	(*AddonUpdateData)(nil),     // 6: riptik.booking.v1.AddonUpdateData
	(*DeleteAddonRequest)(nil),  // 7: riptik.booking.v1.DeleteAddonRequest
	(*ListAddonsResponse)(nil),  // 8: riptik.booking.v1.ListAddonsResponse
	(*GetAddonResponse)(nil),    // 9: riptik.booking.v1.GetAddonResponse
	(*CreateAddonResponse)(nil), // 10: riptik.booking.v1.CreateAddonResponse
	(*UpdateAddonResponse)(nil), // 11: riptik.booking.v1.UpdateAddonResponse
	(*DeleteAddonResponse)(nil), // 12: riptik.booking.v1.DeleteAddonResponse
}
var file_v1_booking_addon_proto_depIdxs = []int32{
	4, // 0: riptik.booking.v1.CreateAddonRequest.data:type_name -> riptik.booking.v1.AddonCreateData
	6, // 1: riptik.booking.v1.UpdateAddonRequest.data:type_name -> riptik.booking.v1.AddonUpdateData
	0, // 2: riptik.booking.v1.ListAddonsResponse.addons:type_name -> riptik.booking.v1.ItemAddon
	0, // 3: riptik.booking.v1.GetAddonResponse.addon:type_name -> riptik.booking.v1.ItemAddon
	0, // 4: riptik.booking.v1.CreateAddonResponse.addon:type_name -> riptik.booking.v1.ItemAddon
	0, // 5: riptik.booking.v1.UpdateAddonResponse.addon:type_name -> riptik.booking.v1.ItemAddon
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_v1_booking_addon_proto_init() }
func file_v1_booking_addon_proto_init() {
	if File_v1_booking_addon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_booking_addon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemAddon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_booking_addon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAddonsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_booking_addon_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAddonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_booking_addon_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAddonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_booking_addon_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddonCreateData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_booking_addon_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAddonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_booking_addon_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddonUpdateData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_booking_addon_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAddonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_booking_addon_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAddonsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_booking_addon_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAddonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_booking_addon_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAddonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_booking_addon_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAddonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_booking_addon_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAddonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_booking_addon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_booking_addon_proto_goTypes,
		DependencyIndexes: file_v1_booking_addon_proto_depIdxs,
		MessageInfos:      file_v1_booking_addon_proto_msgTypes,
	}.Build()
	File_v1_booking_addon_proto = out.File
	file_v1_booking_addon_proto_rawDesc = nil
	file_v1_booking_addon_proto_goTypes = nil
	file_v1_booking_addon_proto_depIdxs = nil
}
