// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: v1/booking/item_variation.proto

package booking

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ItemVariation — biến thể của Item (vd size S/M/L), có thể override giá riêng. Model đã tồn tại từ
// lâu (booking-core/internal/models/event.go) và ĐANG dùng thật trong luồng đặt vé/quota (không phải
// leftover), nhưng CHƯA từng có NATS API nào để list — bổ sung cho tính năng export/import YAML
// (mantik-export-import-yaml.md), read-only (chỉ list, không thêm Create/Update/Delete — ngoài phạm vi
// yêu cầu hiện tại).
type ItemVariation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ItemId        int64                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Value         map[string]string      `protobuf:"bytes,3,rep,name=value,proto3" json:"value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // i18n label (vd {"vi": "Size L"})
	Active        bool                   `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	DefaultPrice  string                 `protobuf:"bytes,5,opt,name=default_price,json=defaultPrice,proto3" json:"default_price,omitempty"` // decimal-as-string, rỗng = dùng giá gốc của Item
	Created       string                 `protobuf:"bytes,6,opt,name=created,proto3" json:"created,omitempty"`                               // ISO datetime
	LastModified  string                 `protobuf:"bytes,7,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"` // ISO datetime
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemVariation) Reset() {
	*x = ItemVariation{}
	mi := &file_v1_booking_item_variation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemVariation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemVariation) ProtoMessage() {}

func (x *ItemVariation) ProtoReflect() protoreflect.Message {
	mi := &file_v1_booking_item_variation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemVariation.ProtoReflect.Descriptor instead.
func (*ItemVariation) Descriptor() ([]byte, []int) {
	return file_v1_booking_item_variation_proto_rawDescGZIP(), []int{0}
}

func (x *ItemVariation) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ItemVariation) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ItemVariation) GetValue() map[string]string {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ItemVariation) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *ItemVariation) GetDefaultPrice() string {
	if x != nil {
		return x.DefaultPrice
	}
	return ""
}

func (x *ItemVariation) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *ItemVariation) GetLastModified() string {
	if x != nil {
		return x.LastModified
	}
	return ""
}

type ListItemVariationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int64                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemVariationsRequest) Reset() {
	*x = ListItemVariationsRequest{}
	mi := &file_v1_booking_item_variation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemVariationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemVariationsRequest) ProtoMessage() {}

func (x *ListItemVariationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_booking_item_variation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemVariationsRequest.ProtoReflect.Descriptor instead.
func (*ListItemVariationsRequest) Descriptor() ([]byte, []int) {
	return file_v1_booking_item_variation_proto_rawDescGZIP(), []int{1}
}

func (x *ListItemVariationsRequest) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type ListItemVariationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Variations    []*ItemVariation       `protobuf:"bytes,2,rep,name=variations,proto3" json:"variations,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemVariationsResponse) Reset() {
	*x = ListItemVariationsResponse{}
	mi := &file_v1_booking_item_variation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemVariationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemVariationsResponse) ProtoMessage() {}

func (x *ListItemVariationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_booking_item_variation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemVariationsResponse.ProtoReflect.Descriptor instead.
func (*ListItemVariationsResponse) Descriptor() ([]byte, []int) {
	return file_v1_booking_item_variation_proto_rawDescGZIP(), []int{2}
}

func (x *ListItemVariationsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListItemVariationsResponse) GetVariations() []*ItemVariation {
	if x != nil {
		return x.Variations
	}
	return nil
}

func (x *ListItemVariationsResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ListItemVariationsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_v1_booking_item_variation_proto protoreflect.FileDescriptor

const file_v1_booking_item_variation_proto_rawDesc = "" +
	"\n" +
	"\x1fv1/booking/item_variation.proto\x12\x11riptik.booking.v1\"\xb1\x02\n" +
	"\rItemVariation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x03R\x06itemId\x12A\n" +
	"\x05value\x18\x03 \x03(\v2+.riptik.booking.v1.ItemVariation.ValueEntryR\x05value\x12\x16\n" +
	"\x06active\x18\x04 \x01(\bR\x06active\x12#\n" +
	"\rdefault_price\x18\x05 \x01(\tR\fdefaultPrice\x12\x18\n" +
	"\acreated\x18\x06 \x01(\tR\acreated\x12#\n" +
	"\rlast_modified\x18\a \x01(\tR\flastModified\x1a8\n" +
	"\n" +
	"ValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\x19ListItemVariationsRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x03R\x06itemId\"\xbc\x01\n" +
	"\x1aListItemVariationsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12@\n" +
	"\n" +
	"variations\x18\x02 \x03(\v2 .riptik.booking.v1.ItemVariationR\n" +
	"variations\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessageB*Z(github.com/riptik/services/pb/v1/bookingb\x06proto3"

var (
	file_v1_booking_item_variation_proto_rawDescOnce sync.Once
	file_v1_booking_item_variation_proto_rawDescData []byte
)

func file_v1_booking_item_variation_proto_rawDescGZIP() []byte {
	file_v1_booking_item_variation_proto_rawDescOnce.Do(func() {
		file_v1_booking_item_variation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_booking_item_variation_proto_rawDesc), len(file_v1_booking_item_variation_proto_rawDesc)))
	})
	return file_v1_booking_item_variation_proto_rawDescData
}

var file_v1_booking_item_variation_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_booking_item_variation_proto_goTypes = []any{
	(*ItemVariation)(nil),              // 0: riptik.booking.v1.ItemVariation
	(*ListItemVariationsRequest)(nil),  // 1: riptik.booking.v1.ListItemVariationsRequest
	(*ListItemVariationsResponse)(nil), // 2: riptik.booking.v1.ListItemVariationsResponse
	nil,                                // 3: riptik.booking.v1.ItemVariation.ValueEntry
}
var file_v1_booking_item_variation_proto_depIdxs = []int32{
	3, // 0: riptik.booking.v1.ItemVariation.value:type_name -> riptik.booking.v1.ItemVariation.ValueEntry
	0, // 1: riptik.booking.v1.ListItemVariationsResponse.variations:type_name -> riptik.booking.v1.ItemVariation
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_booking_item_variation_proto_init() }
func file_v1_booking_item_variation_proto_init() {
	if File_v1_booking_item_variation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_booking_item_variation_proto_rawDesc), len(file_v1_booking_item_variation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_booking_item_variation_proto_goTypes,
		DependencyIndexes: file_v1_booking_item_variation_proto_depIdxs,
		MessageInfos:      file_v1_booking_item_variation_proto_msgTypes,
	}.Build()
	File_v1_booking_item_variation_proto = out.File
	file_v1_booking_item_variation_proto_goTypes = nil
	file_v1_booking_item_variation_proto_depIdxs = nil
}
